export enum StatsigEvents {
  EVENT = 'generic_event',
  REQUEST_START_EVENT = 'web_request_start',
  REQUEST_CONTACT_INFO_EVENT = 'web_request_contact_info',
  REQUEST_PREFERRED_TIME_WINDOW = 'web_preferred_time_window',
  REQUEST_ADDRESS_EVENT = 'web_request_address',
  REQUEST_REQUESTOR_TYPE_EVENT = 'web_request_requestor_type',
  REQUEST_PERSONAL_INFO_EVENT = 'web_request_personal_info',
  REQUEST_SYMPTOMS_EVENT = 'web_request_symptoms',
  REQUEST_SUBMITTED_EVENT = 'web_request_submitted',
  REQUEST_HOW_IT_WORKS_EVENT = 'web_request_how_it_works',
  REQUEST_SYMPTOMS_SELECTION_EVENT = 'web_request_symptom_selection',
  ADD_REQUIRED_INSURANCE_PAGE_EVENT = 'add_insurance_pageview',
  REQUEST_COMPLETE_CONFIRMATION_OPTIONAL_INSURANCE_EVENT = 'request_complete_confirmation_insurance_optional',
  ADD_INSURANCE_PHOTO_EVENT = 'add_insurance_photo_attempt',
  ADD_INSURANCE_MANUALLY_EVENT = 'add_insurance_manual_attempt',
  NO_INSURANCE_EVENT = 'add_insurance_no_insurance',
  ADD_INSURANCE_PHOTO_SUCCESS_EVENT = 'add_insurance_photo_success',
  ADD_INSURANCE_MANUALLY_SUCCESS_EVENT = 'add_insurance_manual_success',
  ADD_INSURANCE_MANUALLY_SAVE_EVENT = 'add_insurance_manual_save',
  ADD_INSURANCE_PHOTO_SUBMIT_EVENT = 'add_insurance_photo_submit_images',
  ADD_INSURANCE_SUBMIT_EVENT = 'add_insurance_submit_visit_request',
  ADD_INSURANCE_SUBMIT_SUCCESS_EVENT = 'request_complete_confirmation_insurance_added',
  NO_INSURANCE_SUBMIT_SUCCESS_EVENT = 'request_complete_confirmation_no_insurance',
}

export enum StatsigCategories {
  FORM_ERRORS = 'form errors',
  ERRORS = 'errors',
  ERROR_404 = '404',
  ERROR_500 = '500',
  BROKEN_IMAGE = 'broken image',
}
export enum StatsigActions {
  ADDED_CONTACT_INFO = 'added contact info',
  ADDED_PREFERRED_TIME_WINDOW = 'added preferred time window',
  ADDED_ADDRESS = 'added address',
  ADDED_REQUESTOR_TYPE = 'added requestor type',
  ADDED_PERSONAL_INFO = 'added personal info',
  ADDED_SYMPTOMS = 'added symptoms',
  SUBMIT_REQUEST = 'submitted care request',
  COMPLETED_CARE_REQUEST = 'completed care request',
  WEB_REQUEST_TYPE = 'web',
  MOBILE_WEB_REQUEST_TYPE = 'mobile_web',
}
export enum StatsigLabels {
  PAGE_URL = 'Page URL',
  DEFAULT_LABEL = '-',
  SHARE = 'share',
  IMAGE = 'image',
  CLOSE = 'close',
  PREVIOUS = 'previous',
  NEXT = 'next',
}
export enum StatsigPageCategory {
  REQUEST_CONTACT_INFO = 'contact_info',
  REQUEST_PREFERRED_TIME_WINDOW = 'request_preferred_time_window',
  REQUEST_ADDRESS = 'request_address',
  REQUEST_CARE_FOR = 'request_care_for',
  REQUEST_HELP = 'request_help',
  REQUEST_DETAILS = 'request_personal_info',
  REQUEST_INSURNACE = 'request_insurance',
  REQUEST_HOW_IT_WORKS = 'request_how_it_works',
  ERROR_404 = '404',
  ERROR_500 = '500',
  ERROR = 'error',
}
