export const PEER_RANKINGS_TEST_IDS = {
  SECTION_PREFIX: 'peer-rankings',
};

export const MARQUEE_LEADER_PLACEHOLDER_RANKS = [1, 2, 3];

export const MARQUEE_LEADER_CURRENT_PROVIDER_PLACEHOLDER_RANK = 123;
