/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelVisitRequest
 */
export interface CancelVisitRequest {
    /**
     * care_request_id represents the ID of the Care Request to be canceled.
     * @type {string}
     * @memberof CancelVisitRequest
     */
    careRequestId: string;
}

/**
 * Check if a given object implements the CancelVisitRequest interface.
 */
export function instanceOfCancelVisitRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "careRequestId" in value;

    return isInstance;
}

export function CancelVisitRequestFromJSON(json: any): CancelVisitRequest {
    return CancelVisitRequestFromJSONTyped(json, false);
}

export function CancelVisitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelVisitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'careRequestId': json['care_request_id'],
    };
}

export function CancelVisitRequestToJSON(value?: CancelVisitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'care_request_id': value.careRequestId,
    };
}

