/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CanScheduleVisitRequest
 */
export interface CanScheduleVisitRequest {
    /**
     * care_request_id represents the ID of the Care Request to be checked.
     * @type {string}
     * @memberof CanScheduleVisitRequest
     */
    careRequestId: string;
    /**
     * patient_availability_start_time represents the start time of the patient's
     * availability in Unix format.
     * @type {string}
     * @memberof CanScheduleVisitRequest
     */
    patientAvailabilityStartTime: string;
    /**
     * patient_availability_end_time represents the end time of the patient's
     * availability in Unix format.
     * @type {string}
     * @memberof CanScheduleVisitRequest
     */
    patientAvailabilityEndTime: string;
}

/**
 * Check if a given object implements the CanScheduleVisitRequest interface.
 */
export function instanceOfCanScheduleVisitRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "careRequestId" in value;
    isInstance = isInstance && "patientAvailabilityStartTime" in value;
    isInstance = isInstance && "patientAvailabilityEndTime" in value;

    return isInstance;
}

export function CanScheduleVisitRequestFromJSON(json: any): CanScheduleVisitRequest {
    return CanScheduleVisitRequestFromJSONTyped(json, false);
}

export function CanScheduleVisitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CanScheduleVisitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'careRequestId': json['care_request_id'],
        'patientAvailabilityStartTime': json['patient_availability_start_time'],
        'patientAvailabilityEndTime': json['patient_availability_end_time'],
    };
}

export function CanScheduleVisitRequestToJSON(value?: CanScheduleVisitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'care_request_id': value.careRequestId,
        'patient_availability_start_time': value.patientAvailabilityStartTime,
        'patient_availability_end_time': value.patientAvailabilityEndTime,
    };
}

