/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PhoneNumber } from './PhoneNumber';
import {
    PhoneNumberFromJSON,
    PhoneNumberFromJSONTyped,
    PhoneNumberToJSON,
} from './PhoneNumber';

/**
 * 
 * @export
 * @interface Car
 */
export interface Car {
    /**
     * id represents the ID of the Car.
     * @type {string}
     * @memberof Car
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    name?: string;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof Car
     */
    phoneNumber?: PhoneNumber;
}

/**
 * Check if a given object implements the Car interface.
 */
export function instanceOfCar(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarFromJSON(json: any): Car {
    return CarFromJSONTyped(json, false);
}

export function CarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Car {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : PhoneNumberFromJSON(json['phone_number']),
    };
}

export function CarToJSON(value?: Car | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'phone_number': PhoneNumberToJSON(value.phoneNumber),
    };
}

