/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateEpisodeTask } from './CreateEpisodeTask';
import {
    CreateEpisodeTaskFromJSON,
    CreateEpisodeTaskFromJSONTyped,
    CreateEpisodeTaskToJSON,
} from './CreateEpisodeTask';

/**
 * 
 * @export
 * @interface CareManagerServiceCreateEpisodeTasksRequest
 */
export interface CareManagerServiceCreateEpisodeTasksRequest {
    /**
     * tasks represents a collection of new Tasks to be created.
     * @type {Array<CreateEpisodeTask>}
     * @memberof CareManagerServiceCreateEpisodeTasksRequest
     */
    tasks: Array<CreateEpisodeTask>;
}

/**
 * Check if a given object implements the CareManagerServiceCreateEpisodeTasksRequest interface.
 */
export function instanceOfCareManagerServiceCreateEpisodeTasksRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tasks" in value;

    return isInstance;
}

export function CareManagerServiceCreateEpisodeTasksRequestFromJSON(json: any): CareManagerServiceCreateEpisodeTasksRequest {
    return CareManagerServiceCreateEpisodeTasksRequestFromJSONTyped(json, false);
}

export function CareManagerServiceCreateEpisodeTasksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceCreateEpisodeTasksRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(CreateEpisodeTaskFromJSON)),
    };
}

export function CareManagerServiceCreateEpisodeTasksRequestToJSON(value?: CareManagerServiceCreateEpisodeTasksRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tasks': ((value.tasks as Array<any>).map(CreateEpisodeTaskToJSON)),
    };
}

