/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateTaskRequest
 */
export interface CareManagerServiceUpdateTaskRequest {
    /**
     * Required. task_type represents the type of Task to be updated.
     * @type {string}
     * @memberof CareManagerServiceUpdateTaskRequest
     */
    taskType: string;
    /**
     * Required. task represents the description or the content of the
     * task.
     * @type {string}
     * @memberof CareManagerServiceUpdateTaskRequest
     */
    task: string;
    /**
     * Required. status represents the status of the Task.
     * @type {string}
     * @memberof CareManagerServiceUpdateTaskRequest
     */
    status: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateTaskRequest interface.
 */
export function instanceOfCareManagerServiceUpdateTaskRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskType" in value;
    isInstance = isInstance && "task" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function CareManagerServiceUpdateTaskRequestFromJSON(json: any): CareManagerServiceUpdateTaskRequest {
    return CareManagerServiceUpdateTaskRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateTaskRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskType': json['task_type'],
        'task': json['task'],
        'status': json['status'],
    };
}

export function CareManagerServiceUpdateTaskRequestToJSON(value?: CareManagerServiceUpdateTaskRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_type': value.taskType,
        'task': value.task,
        'status': value.status,
    };
}

