/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceRejectServiceRequestRequest
 */
export interface CareManagerServiceRejectServiceRequestRequest {
    /**
     * reject_reason is a string representing a reason for the rejection of a
     * ServiceRequest.
     * @type {string}
     * @memberof CareManagerServiceRejectServiceRequestRequest
     */
    rejectReason: string;
}

/**
 * Check if a given object implements the CareManagerServiceRejectServiceRequestRequest interface.
 */
export function instanceOfCareManagerServiceRejectServiceRequestRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rejectReason" in value;

    return isInstance;
}

export function CareManagerServiceRejectServiceRequestRequestFromJSON(json: any): CareManagerServiceRejectServiceRequestRequest {
    return CareManagerServiceRejectServiceRequestRequestFromJSONTyped(json, false);
}

export function CareManagerServiceRejectServiceRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceRejectServiceRequestRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rejectReason': json['reject_reason'],
    };
}

export function CareManagerServiceRejectServiceRequestRequestToJSON(value?: CareManagerServiceRejectServiceRequestRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reject_reason': value.rejectReason,
    };
}

