/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EHRAppointment } from './EHRAppointment';
import {
    EHRAppointmentFromJSON,
    EHRAppointmentFromJSONTyped,
    EHRAppointmentToJSON,
} from './EHRAppointment';

/**
 * 
 * @export
 * @interface CareManagerServiceUpdateEHRAppointmentRequest
 */
export interface CareManagerServiceUpdateEHRAppointmentRequest {
    /**
     * 
     * @type {EHRAppointment}
     * @memberof CareManagerServiceUpdateEHRAppointmentRequest
     */
    appointment?: EHRAppointment;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateEHRAppointmentRequest interface.
 */
export function instanceOfCareManagerServiceUpdateEHRAppointmentRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdateEHRAppointmentRequestFromJSON(json: any): CareManagerServiceUpdateEHRAppointmentRequest {
    return CareManagerServiceUpdateEHRAppointmentRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateEHRAppointmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateEHRAppointmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appointment': !exists(json, 'appointment') ? undefined : EHRAppointmentFromJSON(json['appointment']),
    };
}

export function CareManagerServiceUpdateEHRAppointmentRequestToJSON(value?: CareManagerServiceUpdateEHRAppointmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appointment': EHRAppointmentToJSON(value.appointment),
    };
}

