/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateExternalCareProviderRequest
 */
export interface CareManagerServiceUpdateExternalCareProviderRequest {
    /**
     * name represents the name of the ExternalCareProvider.
     * @type {string}
     * @memberof CareManagerServiceUpdateExternalCareProviderRequest
     */
    name?: string;
    /**
     * phone_number represents the phone number of the ExternalCareProvider.
     * @type {string}
     * @memberof CareManagerServiceUpdateExternalCareProviderRequest
     */
    phoneNumber?: string;
    /**
     * fax_number represents the fax number of the ExternalCareProvider.
     * @type {string}
     * @memberof CareManagerServiceUpdateExternalCareProviderRequest
     */
    faxNumber?: string;
    /**
     * address represents the full string representation of the
     * ExternalCareProvider address.
     * @type {string}
     * @memberof CareManagerServiceUpdateExternalCareProviderRequest
     */
    address?: string;
    /**
     * provider_type_id represents the ID of the ProviderType that this
     * ExternalCareProvider is assigned to.
     * @type {string}
     * @memberof CareManagerServiceUpdateExternalCareProviderRequest
     */
    providerTypeId?: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateExternalCareProviderRequest interface.
 */
export function instanceOfCareManagerServiceUpdateExternalCareProviderRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdateExternalCareProviderRequestFromJSON(json: any): CareManagerServiceUpdateExternalCareProviderRequest {
    return CareManagerServiceUpdateExternalCareProviderRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateExternalCareProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateExternalCareProviderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'faxNumber': !exists(json, 'fax_number') ? undefined : json['fax_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'providerTypeId': !exists(json, 'provider_type_id') ? undefined : json['provider_type_id'],
    };
}

export function CareManagerServiceUpdateExternalCareProviderRequestToJSON(value?: CareManagerServiceUpdateExternalCareProviderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'phone_number': value.phoneNumber,
        'fax_number': value.faxNumber,
        'address': value.address,
        'provider_type_id': value.providerTypeId,
    };
}

