/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateVisitSummaryRequest
 */
export interface CareManagerServiceUpdateVisitSummaryRequest {
    /**
     * Required. body represents the new VisitSummary content.
     * @type {string}
     * @memberof CareManagerServiceUpdateVisitSummaryRequest
     */
    body: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateVisitSummaryRequest interface.
 */
export function instanceOfCareManagerServiceUpdateVisitSummaryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "body" in value;

    return isInstance;
}

export function CareManagerServiceUpdateVisitSummaryRequestFromJSON(json: any): CareManagerServiceUpdateVisitSummaryRequest {
    return CareManagerServiceUpdateVisitSummaryRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateVisitSummaryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateVisitSummaryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function CareManagerServiceUpdateVisitSummaryRequestToJSON(value?: CareManagerServiceUpdateVisitSummaryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
    };
}

