/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateNoteRequest
 */
export interface CareManagerServiceUpdateNoteRequest {
    /**
     * details represents the description or the content of the Note.
     * @type {string}
     * @memberof CareManagerServiceUpdateNoteRequest
     */
    details?: string;
    /**
     * note_kind represents the type of the note, whether it is a general note, a
     * daily update, etc.
     * @type {string}
     * @memberof CareManagerServiceUpdateNoteRequest
     */
    noteKind?: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateNoteRequest interface.
 */
export function instanceOfCareManagerServiceUpdateNoteRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdateNoteRequestFromJSON(json: any): CareManagerServiceUpdateNoteRequest {
    return CareManagerServiceUpdateNoteRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateNoteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'details': !exists(json, 'details') ? undefined : json['details'],
        'noteKind': !exists(json, 'note_kind') ? undefined : json['note_kind'],
    };
}

export function CareManagerServiceUpdateNoteRequestToJSON(value?: CareManagerServiceUpdateNoteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'details': value.details,
        'note_kind': value.noteKind,
    };
}

