/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateVisitEpisodeRequest
 */
export interface CareManagerServiceUpdateVisitEpisodeRequest {
    /**
     * Required. episode_id represents the ID of the Episode the Visit will
     * be assigned to.
     * @type {string}
     * @memberof CareManagerServiceUpdateVisitEpisodeRequest
     */
    episodeId: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateVisitEpisodeRequest interface.
 */
export function instanceOfCareManagerServiceUpdateVisitEpisodeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "episodeId" in value;

    return isInstance;
}

export function CareManagerServiceUpdateVisitEpisodeRequestFromJSON(json: any): CareManagerServiceUpdateVisitEpisodeRequest {
    return CareManagerServiceUpdateVisitEpisodeRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateVisitEpisodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateVisitEpisodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'episodeId': json['episode_id'],
    };
}

export function CareManagerServiceUpdateVisitEpisodeRequestToJSON(value?: CareManagerServiceUpdateVisitEpisodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'episode_id': value.episodeId,
    };
}

