/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdatePharmacyRequest
 */
export interface CareManagerServiceUpdatePharmacyRequest {
    /**
     * name represents the name of the Pharmacy.
     * @type {string}
     * @memberof CareManagerServiceUpdatePharmacyRequest
     */
    name?: string;
    /**
     * phone_number represents the phone number of the Pharmacy.
     * @type {string}
     * @memberof CareManagerServiceUpdatePharmacyRequest
     */
    phoneNumber?: string;
    /**
     * fax_number represents the fax number of the Pharmacy.
     * @type {string}
     * @memberof CareManagerServiceUpdatePharmacyRequest
     */
    faxNumber?: string;
    /**
     * address represents the full string representation of the Pharmacy address.
     * @type {string}
     * @memberof CareManagerServiceUpdatePharmacyRequest
     */
    address?: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdatePharmacyRequest interface.
 */
export function instanceOfCareManagerServiceUpdatePharmacyRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdatePharmacyRequestFromJSON(json: any): CareManagerServiceUpdatePharmacyRequest {
    return CareManagerServiceUpdatePharmacyRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdatePharmacyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdatePharmacyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'faxNumber': !exists(json, 'fax_number') ? undefined : json['fax_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function CareManagerServiceUpdatePharmacyRequestToJSON(value?: CareManagerServiceUpdatePharmacyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'phone_number': value.phoneNumber,
        'fax_number': value.faxNumber,
        'address': value.address,
    };
}

