/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateServiceRequestRequest
 */
export interface CareManagerServiceUpdateServiceRequestRequest {
    /**
     * assigned_user_id represents the id of a User that will be assigned to the
     * ServiceRequest.
     * @type {string}
     * @memberof CareManagerServiceUpdateServiceRequestRequest
     */
    assignedUserId?: string;
    /**
     * status_id represents the ServiceRequestStatus id that the ServiceRequest
     * has.
     * @type {string}
     * @memberof CareManagerServiceUpdateServiceRequestRequest
     */
    statusId?: string;
    /**
     * cms_number represents the CMS affiliation number for the ServiceRequest.
     * @type {string}
     * @memberof CareManagerServiceUpdateServiceRequestRequest
     */
    cmsNumber?: string;
    /**
     * is_insurance_verified is a flag stating if a ServiceRequest's insurance has
     * been verified.
     * @type {boolean}
     * @memberof CareManagerServiceUpdateServiceRequestRequest
     */
    isInsuranceVerified?: boolean;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateServiceRequestRequest interface.
 */
export function instanceOfCareManagerServiceUpdateServiceRequestRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdateServiceRequestRequestFromJSON(json: any): CareManagerServiceUpdateServiceRequestRequest {
    return CareManagerServiceUpdateServiceRequestRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateServiceRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateServiceRequestRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assignedUserId': !exists(json, 'assigned_user_id') ? undefined : json['assigned_user_id'],
        'statusId': !exists(json, 'status_id') ? undefined : json['status_id'],
        'cmsNumber': !exists(json, 'cms_number') ? undefined : json['cms_number'],
        'isInsuranceVerified': !exists(json, 'is_insurance_verified') ? undefined : json['is_insurance_verified'],
    };
}

export function CareManagerServiceUpdateServiceRequestRequestToJSON(value?: CareManagerServiceUpdateServiceRequestRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assigned_user_id': value.assignedUserId,
        'status_id': value.statusId,
        'cms_number': value.cmsNumber,
        'is_insurance_verified': value.isInsuranceVerified,
    };
}

