/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateEpisodeNote } from './CreateEpisodeNote';
import {
    CreateEpisodeNoteFromJSON,
    CreateEpisodeNoteFromJSONTyped,
    CreateEpisodeNoteToJSON,
} from './CreateEpisodeNote';

/**
 * 
 * @export
 * @interface CareManagerServiceCreateEpisodeNoteRequest
 */
export interface CareManagerServiceCreateEpisodeNoteRequest {
    /**
     * 
     * @type {CreateEpisodeNote}
     * @memberof CareManagerServiceCreateEpisodeNoteRequest
     */
    note?: CreateEpisodeNote;
}

/**
 * Check if a given object implements the CareManagerServiceCreateEpisodeNoteRequest interface.
 */
export function instanceOfCareManagerServiceCreateEpisodeNoteRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceCreateEpisodeNoteRequestFromJSON(json: any): CareManagerServiceCreateEpisodeNoteRequest {
    return CareManagerServiceCreateEpisodeNoteRequestFromJSONTyped(json, false);
}

export function CareManagerServiceCreateEpisodeNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceCreateEpisodeNoteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'note': !exists(json, 'note') ? undefined : CreateEpisodeNoteFromJSON(json['note']),
    };
}

export function CareManagerServiceCreateEpisodeNoteRequestToJSON(value?: CareManagerServiceCreateEpisodeNoteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'note': CreateEpisodeNoteToJSON(value.note),
    };
}

