/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateVisitRequest
 */
export interface CareManagerServiceUpdateVisitRequest {
    /**
     * visit_type_id is the ID to the visit_type entry that
     * is going to be updated for the Visit.
     * @type {string}
     * @memberof CareManagerServiceUpdateVisitRequest
     */
    visitTypeId?: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateVisitRequest interface.
 */
export function instanceOfCareManagerServiceUpdateVisitRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdateVisitRequestFromJSON(json: any): CareManagerServiceUpdateVisitRequest {
    return CareManagerServiceUpdateVisitRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateVisitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateVisitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'visitTypeId': !exists(json, 'visit_type_id') ? undefined : json['visit_type_id'],
    };
}

export function CareManagerServiceUpdateVisitRequestToJSON(value?: CareManagerServiceUpdateVisitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'visit_type_id': value.visitTypeId,
    };
}

