/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateMedicalDecisionMakerRequest
 */
export interface CareManagerServiceUpdateMedicalDecisionMakerRequest {
    /**
     * first_name represents the first name of the MedicalDecisionMaker.
     * @type {string}
     * @memberof CareManagerServiceUpdateMedicalDecisionMakerRequest
     */
    firstName?: string;
    /**
     * last_name represents the last name of the MedicalDecisionMaker.
     * @type {string}
     * @memberof CareManagerServiceUpdateMedicalDecisionMakerRequest
     */
    lastName?: string;
    /**
     * phone_number represents the phone number of the MedicalDecisionMaker.
     * @type {string}
     * @memberof CareManagerServiceUpdateMedicalDecisionMakerRequest
     */
    phoneNumber?: string;
    /**
     * address represents the full string representation of the
     * MedicalDecisionMaker address.
     * @type {string}
     * @memberof CareManagerServiceUpdateMedicalDecisionMakerRequest
     */
    address?: string;
    /**
     * relationship represents the relation the MedicalDecisionMaker has with the
     * patient it is assigned to, like "parent", "tutor", etc.
     * @type {string}
     * @memberof CareManagerServiceUpdateMedicalDecisionMakerRequest
     */
    relationship?: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateMedicalDecisionMakerRequest interface.
 */
export function instanceOfCareManagerServiceUpdateMedicalDecisionMakerRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdateMedicalDecisionMakerRequestFromJSON(json: any): CareManagerServiceUpdateMedicalDecisionMakerRequest {
    return CareManagerServiceUpdateMedicalDecisionMakerRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateMedicalDecisionMakerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateMedicalDecisionMakerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'relationship': !exists(json, 'relationship') ? undefined : json['relationship'],
    };
}

export function CareManagerServiceUpdateMedicalDecisionMakerRequestToJSON(value?: CareManagerServiceUpdateMedicalDecisionMakerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'last_name': value.lastName,
        'phone_number': value.phoneNumber,
        'address': value.address,
        'relationship': value.relationship,
    };
}

