/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceScheduleServiceRequestRequest
 */
export interface CareManagerServiceScheduleServiceRequestRequest {
    /**
     * patient_availability_start_time_sec represents the start time of the
     * patient's availability in Unix format
     * @type {string}
     * @memberof CareManagerServiceScheduleServiceRequestRequest
     */
    patientAvailabilityStartTimeSec?: string;
    /**
     * patient_availability_end_time represents the end time of the patient's
     * availability in Unix format
     * @type {string}
     * @memberof CareManagerServiceScheduleServiceRequestRequest
     */
    patientAvailabilityEndTimeSec?: string;
    /**
     * care_request_id represents the ID of the Care Request to be scheduled.
     * @type {string}
     * @memberof CareManagerServiceScheduleServiceRequestRequest
     */
    careRequestId?: string;
}

/**
 * Check if a given object implements the CareManagerServiceScheduleServiceRequestRequest interface.
 */
export function instanceOfCareManagerServiceScheduleServiceRequestRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceScheduleServiceRequestRequestFromJSON(json: any): CareManagerServiceScheduleServiceRequestRequest {
    return CareManagerServiceScheduleServiceRequestRequestFromJSONTyped(json, false);
}

export function CareManagerServiceScheduleServiceRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceScheduleServiceRequestRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientAvailabilityStartTimeSec': !exists(json, 'patient_availability_start_time_sec') ? undefined : json['patient_availability_start_time_sec'],
        'patientAvailabilityEndTimeSec': !exists(json, 'patient_availability_end_time_sec') ? undefined : json['patient_availability_end_time_sec'],
        'careRequestId': !exists(json, 'care_request_id') ? undefined : json['care_request_id'],
    };
}

export function CareManagerServiceScheduleServiceRequestRequestToJSON(value?: CareManagerServiceScheduleServiceRequestRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_availability_start_time_sec': value.patientAvailabilityStartTimeSec,
        'patient_availability_end_time_sec': value.patientAvailabilityEndTimeSec,
        'care_request_id': value.careRequestId,
    };
}

