/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerServiceUpdateCallVisitRequest
 */
export interface CareManagerServiceUpdateCallVisitRequest {
    /**
     * visit_type_id is the id of the VisitType entry associated with
     * this Visit.
     * @type {string}
     * @memberof CareManagerServiceUpdateCallVisitRequest
     */
    visitTypeId?: string;
    /**
     * summary represents the summary body associated to this visit that is going
     * to be updated.
     * @type {string}
     * @memberof CareManagerServiceUpdateCallVisitRequest
     */
    summary?: string;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateCallVisitRequest interface.
 */
export function instanceOfCareManagerServiceUpdateCallVisitRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdateCallVisitRequestFromJSON(json: any): CareManagerServiceUpdateCallVisitRequest {
    return CareManagerServiceUpdateCallVisitRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateCallVisitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateCallVisitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'visitTypeId': !exists(json, 'visit_type_id') ? undefined : json['visit_type_id'],
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
    };
}

export function CareManagerServiceUpdateCallVisitRequestToJSON(value?: CareManagerServiceUpdateCallVisitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'visit_type_id': value.visitTypeId,
        'summary': value.summary,
    };
}

