/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateVisitStatusOption } from './UpdateVisitStatusOption';
import {
    UpdateVisitStatusOptionFromJSON,
    UpdateVisitStatusOptionFromJSONTyped,
    UpdateVisitStatusOptionToJSON,
} from './UpdateVisitStatusOption';

/**
 * 
 * @export
 * @interface CareManagerServiceUpdateVisitStatusRequest
 */
export interface CareManagerServiceUpdateVisitStatusRequest {
    /**
     * 
     * @type {UpdateVisitStatusOption}
     * @memberof CareManagerServiceUpdateVisitStatusRequest
     */
    status?: UpdateVisitStatusOption;
}

/**
 * Check if a given object implements the CareManagerServiceUpdateVisitStatusRequest interface.
 */
export function instanceOfCareManagerServiceUpdateVisitStatusRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CareManagerServiceUpdateVisitStatusRequestFromJSON(json: any): CareManagerServiceUpdateVisitStatusRequest {
    return CareManagerServiceUpdateVisitStatusRequestFromJSONTyped(json, false);
}

export function CareManagerServiceUpdateVisitStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerServiceUpdateVisitStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : UpdateVisitStatusOptionFromJSON(json['status']),
    };
}

export function CareManagerServiceUpdateVisitStatusRequestToJSON(value?: CareManagerServiceUpdateVisitStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': UpdateVisitStatusOptionToJSON(value.status),
    };
}

