/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskTemplate } from './TaskTemplate';
import {
    TaskTemplateFromJSON,
    TaskTemplateFromJSONTyped,
    TaskTemplateToJSON,
} from './TaskTemplate';

/**
 * 
 * @export
 * @interface CreateTaskTemplateResponse
 */
export interface CreateTaskTemplateResponse {
    /**
     * 
     * @type {TaskTemplate}
     * @memberof CreateTaskTemplateResponse
     */
    taskTemplate?: TaskTemplate;
}

/**
 * Check if a given object implements the CreateTaskTemplateResponse interface.
 */
export function instanceOfCreateTaskTemplateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateTaskTemplateResponseFromJSON(json: any): CreateTaskTemplateResponse {
    return CreateTaskTemplateResponseFromJSONTyped(json, false);
}

export function CreateTaskTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskTemplateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskTemplate': !exists(json, 'task_template') ? undefined : TaskTemplateFromJSON(json['task_template']),
    };
}

export function CreateTaskTemplateResponseToJSON(value?: CreateTaskTemplateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_template': TaskTemplateToJSON(value.taskTemplate),
    };
}

