/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MedicalDecisionMaker } from './MedicalDecisionMaker';
import {
    MedicalDecisionMakerFromJSON,
    MedicalDecisionMakerFromJSONTyped,
    MedicalDecisionMakerToJSON,
} from './MedicalDecisionMaker';

/**
 * 
 * @export
 * @interface CreateMedicalDecisionMakerResponse
 */
export interface CreateMedicalDecisionMakerResponse {
    /**
     * 
     * @type {MedicalDecisionMaker}
     * @memberof CreateMedicalDecisionMakerResponse
     */
    medicalDecisionMaker?: MedicalDecisionMaker;
    /**
     * patient_medical_decision_makers is the list of all entities
     * associated with the Patient whose MedicalDecisionMaker was created.
     * @type {Array<MedicalDecisionMaker>}
     * @memberof CreateMedicalDecisionMakerResponse
     */
    patientMedicalDecisionMakers?: Array<MedicalDecisionMaker>;
}

/**
 * Check if a given object implements the CreateMedicalDecisionMakerResponse interface.
 */
export function instanceOfCreateMedicalDecisionMakerResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateMedicalDecisionMakerResponseFromJSON(json: any): CreateMedicalDecisionMakerResponse {
    return CreateMedicalDecisionMakerResponseFromJSONTyped(json, false);
}

export function CreateMedicalDecisionMakerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMedicalDecisionMakerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medicalDecisionMaker': !exists(json, 'medical_decision_maker') ? undefined : MedicalDecisionMakerFromJSON(json['medical_decision_maker']),
        'patientMedicalDecisionMakers': !exists(json, 'patient_medical_decision_makers') ? undefined : ((json['patient_medical_decision_makers'] as Array<any>).map(MedicalDecisionMakerFromJSON)),
    };
}

export function CreateMedicalDecisionMakerResponseToJSON(value?: CreateMedicalDecisionMakerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'medical_decision_maker': MedicalDecisionMakerToJSON(value.medicalDecisionMaker),
        'patient_medical_decision_makers': value.patientMedicalDecisionMakers === undefined ? undefined : ((value.patientMedicalDecisionMakers as Array<any>).map(MedicalDecisionMakerToJSON)),
    };
}

