/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExternalCareProviderRequest
 */
export interface CreateExternalCareProviderRequest {
    /**
     * patient_id is the id of the patient for which this provider
     * is going to be associated with.
     * @type {string}
     * @memberof CreateExternalCareProviderRequest
     */
    patientId: string;
    /**
     * name represents the name of the ExternalCareProvider.
     * @type {string}
     * @memberof CreateExternalCareProviderRequest
     */
    name: string;
    /**
     * phone_number represents the phone number of the ExternalCareProvider.
     * @type {string}
     * @memberof CreateExternalCareProviderRequest
     */
    phoneNumber?: string;
    /**
     * fax_number represents the fax number of the ExternalCareProvider.
     * @type {string}
     * @memberof CreateExternalCareProviderRequest
     */
    faxNumber?: string;
    /**
     * address represents the full string representation of the
     * ExternalCareProvider address.
     * @type {string}
     * @memberof CreateExternalCareProviderRequest
     */
    address?: string;
    /**
     * provider_type_id represents the ID of the ProviderType that this
     * ExternalCareProvider is assigned to.
     * @type {string}
     * @memberof CreateExternalCareProviderRequest
     */
    providerTypeId: string;
}

/**
 * Check if a given object implements the CreateExternalCareProviderRequest interface.
 */
export function instanceOfCreateExternalCareProviderRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "providerTypeId" in value;

    return isInstance;
}

export function CreateExternalCareProviderRequestFromJSON(json: any): CreateExternalCareProviderRequest {
    return CreateExternalCareProviderRequestFromJSONTyped(json, false);
}

export function CreateExternalCareProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExternalCareProviderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': json['patient_id'],
        'name': json['name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'faxNumber': !exists(json, 'fax_number') ? undefined : json['fax_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'providerTypeId': json['provider_type_id'],
    };
}

export function CreateExternalCareProviderRequestToJSON(value?: CreateExternalCareProviderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'name': value.name,
        'phone_number': value.phoneNumber,
        'fax_number': value.faxNumber,
        'address': value.address,
        'provider_type_id': value.providerTypeId,
    };
}

