/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInsuranceRequest
 */
export interface CreateInsuranceRequest {
    /**
     * patient_id is the id of the patient for which this insurance is going to be
     * associated with.
     * @type {string}
     * @memberof CreateInsuranceRequest
     */
    patientId: string;
    /**
     * name represents the name of the Insurance.
     * @type {string}
     * @memberof CreateInsuranceRequest
     */
    name: string;
    /**
     * member_id represents the external member_id value of the Insurance, most
     * likely managed by each insurance company.
     * @type {string}
     * @memberof CreateInsuranceRequest
     */
    memberId?: string;
}

/**
 * Check if a given object implements the CreateInsuranceRequest interface.
 */
export function instanceOfCreateInsuranceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateInsuranceRequestFromJSON(json: any): CreateInsuranceRequest {
    return CreateInsuranceRequestFromJSONTyped(json, false);
}

export function CreateInsuranceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInsuranceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': json['patient_id'],
        'name': json['name'],
        'memberId': !exists(json, 'member_id') ? undefined : json['member_id'],
    };
}

export function CreateInsuranceRequestToJSON(value?: CreateInsuranceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'name': value.name,
        'member_id': value.memberId,
    };
}

