/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCallVisitRequest
 */
export interface CreateCallVisitRequest {
    /**
     * Required. episode_id represents the unique identifier of the Episode the
     * Visit belongs to.
     * @type {string}
     * @memberof CreateCallVisitRequest
     */
    episodeId: string;
    /**
     * Required. visit_type_id is the id to the visit_type entry associated with
     * this Visit.
     * @type {string}
     * @memberof CreateCallVisitRequest
     */
    visitTypeId: string;
    /**
     * Required. summary represents the summary body that is going to be created
     * and associated to the visit.
     * @type {string}
     * @memberof CreateCallVisitRequest
     */
    summary: string;
}

/**
 * Check if a given object implements the CreateCallVisitRequest interface.
 */
export function instanceOfCreateCallVisitRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "episodeId" in value;
    isInstance = isInstance && "visitTypeId" in value;
    isInstance = isInstance && "summary" in value;

    return isInstance;
}

export function CreateCallVisitRequestFromJSON(json: any): CreateCallVisitRequest {
    return CreateCallVisitRequestFromJSONTyped(json, false);
}

export function CreateCallVisitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCallVisitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'episodeId': json['episode_id'],
        'visitTypeId': json['visit_type_id'],
        'summary': json['summary'],
    };
}

export function CreateCallVisitRequestToJSON(value?: CreateCallVisitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'episode_id': value.episodeId,
        'visit_type_id': value.visitTypeId,
        'summary': value.summary,
    };
}

