/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Visit } from './Visit';
import {
    VisitFromJSON,
    VisitFromJSONTyped,
    VisitToJSON,
} from './Visit';
import type { VisitSummary } from './VisitSummary';
import {
    VisitSummaryFromJSON,
    VisitSummaryFromJSONTyped,
    VisitSummaryToJSON,
} from './VisitSummary';

/**
 * 
 * @export
 * @interface CreateCallVisitResponse
 */
export interface CreateCallVisitResponse {
    /**
     * 
     * @type {Visit}
     * @memberof CreateCallVisitResponse
     */
    visit?: Visit;
    /**
     * 
     * @type {VisitSummary}
     * @memberof CreateCallVisitResponse
     */
    summary?: VisitSummary;
}

/**
 * Check if a given object implements the CreateCallVisitResponse interface.
 */
export function instanceOfCreateCallVisitResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateCallVisitResponseFromJSON(json: any): CreateCallVisitResponse {
    return CreateCallVisitResponseFromJSONTyped(json, false);
}

export function CreateCallVisitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCallVisitResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'visit': !exists(json, 'visit') ? undefined : VisitFromJSON(json['visit']),
        'summary': !exists(json, 'summary') ? undefined : VisitSummaryFromJSON(json['summary']),
    };
}

export function CreateCallVisitResponseToJSON(value?: CreateCallVisitResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'visit': VisitToJSON(value.visit),
        'summary': VisitSummaryToJSON(value.summary),
    };
}

