/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Task } from './Task';
import {
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './Task';

/**
 * 
 * @export
 * @interface CreateEpisodeTasksResponse
 */
export interface CreateEpisodeTasksResponse {
    /**
     * tasks represents the collection of Tasks created and assigned to the
     * Episode.
     * @type {Array<Task>}
     * @memberof CreateEpisodeTasksResponse
     */
    tasks: Array<Task>;
}

/**
 * Check if a given object implements the CreateEpisodeTasksResponse interface.
 */
export function instanceOfCreateEpisodeTasksResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tasks" in value;

    return isInstance;
}

export function CreateEpisodeTasksResponseFromJSON(json: any): CreateEpisodeTasksResponse {
    return CreateEpisodeTasksResponseFromJSONTyped(json, false);
}

export function CreateEpisodeTasksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEpisodeTasksResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskFromJSON)),
    };
}

export function CreateEpisodeTasksResponseToJSON(value?: CreateEpisodeTasksResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tasks': ((value.tasks as Array<any>).map(TaskToJSON)),
    };
}

