/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Episode } from './Episode';
import {
    EpisodeFromJSON,
    EpisodeFromJSONTyped,
    EpisodeToJSON,
} from './Episode';

/**
 * 
 * @export
 * @interface CreateEpisodeResponse
 */
export interface CreateEpisodeResponse {
    /**
     * 
     * @type {Episode}
     * @memberof CreateEpisodeResponse
     */
    episode?: Episode;
}

/**
 * Check if a given object implements the CreateEpisodeResponse interface.
 */
export function instanceOfCreateEpisodeResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateEpisodeResponseFromJSON(json: any): CreateEpisodeResponse {
    return CreateEpisodeResponseFromJSONTyped(json, false);
}

export function CreateEpisodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEpisodeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'episode': !exists(json, 'episode') ? undefined : EpisodeFromJSON(json['episode']),
    };
}

export function CreateEpisodeResponseToJSON(value?: CreateEpisodeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'episode': EpisodeToJSON(value.episode),
    };
}

