/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMedicalDecisionMakerRequest
 */
export interface CreateMedicalDecisionMakerRequest {
    /**
     * patient_id is the id of the Patient for which this MedicalDecisionMaker.
     * is going to be associated with.
     * @type {string}
     * @memberof CreateMedicalDecisionMakerRequest
     */
    patientId: string;
    /**
     * first_name represents the first name of the MedicalDecisionMaker.
     * @type {string}
     * @memberof CreateMedicalDecisionMakerRequest
     */
    firstName: string;
    /**
     * last_name represents the last name of the MedicalDecisionMaker.
     * @type {string}
     * @memberof CreateMedicalDecisionMakerRequest
     */
    lastName: string;
    /**
     * phone_number represents the phone number of the MedicalDecisionMaker.
     * @type {string}
     * @memberof CreateMedicalDecisionMakerRequest
     */
    phoneNumber?: string;
    /**
     * address represents the full string representation of the
     * MedicalDecisionMaker address.
     * @type {string}
     * @memberof CreateMedicalDecisionMakerRequest
     */
    address?: string;
    /**
     * relationship represents the relation the MedicalDecisionMaker has with the
     * patient it is assigned to, like "parent", "tutor", etc.
     * @type {string}
     * @memberof CreateMedicalDecisionMakerRequest
     */
    relationship?: string;
}

/**
 * Check if a given object implements the CreateMedicalDecisionMakerRequest interface.
 */
export function instanceOfCreateMedicalDecisionMakerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;

    return isInstance;
}

export function CreateMedicalDecisionMakerRequestFromJSON(json: any): CreateMedicalDecisionMakerRequest {
    return CreateMedicalDecisionMakerRequestFromJSONTyped(json, false);
}

export function CreateMedicalDecisionMakerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMedicalDecisionMakerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': json['patient_id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'relationship': !exists(json, 'relationship') ? undefined : json['relationship'],
    };
}

export function CreateMedicalDecisionMakerRequestToJSON(value?: CreateMedicalDecisionMakerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'phone_number': value.phoneNumber,
        'address': value.address,
        'relationship': value.relationship,
    };
}

