/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEHRAppointmentResponse
 */
export interface CreateEHRAppointmentResponse {
    /**
     * ID of created appointment for the specified visit.
     * @type {string}
     * @memberof CreateEHRAppointmentResponse
     */
    appointmentId?: string;
}

/**
 * Check if a given object implements the CreateEHRAppointmentResponse interface.
 */
export function instanceOfCreateEHRAppointmentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateEHRAppointmentResponseFromJSON(json: any): CreateEHRAppointmentResponse {
    return CreateEHRAppointmentResponseFromJSONTyped(json, false);
}

export function CreateEHRAppointmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEHRAppointmentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appointmentId': !exists(json, 'appointment_id') ? undefined : json['appointment_id'],
    };
}

export function CreateEHRAppointmentResponseToJSON(value?: CreateEHRAppointmentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appointment_id': value.appointmentId,
    };
}

