/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePharmacyRequest
 */
export interface CreatePharmacyRequest {
    /**
     * patient_id is the id of the Patient for which this Pharmacy.
     * is going to be associated with.
     * @type {string}
     * @memberof CreatePharmacyRequest
     */
    patientId: string;
    /**
     * name represents the name of the Pharmacy.
     * @type {string}
     * @memberof CreatePharmacyRequest
     */
    name: string;
    /**
     * phone_number represents the phone number of the Pharmacy.
     * @type {string}
     * @memberof CreatePharmacyRequest
     */
    phoneNumber?: string;
    /**
     * fax_number represents the fax number of the Pharmacy.
     * @type {string}
     * @memberof CreatePharmacyRequest
     */
    faxNumber?: string;
    /**
     * address represents the full string representation of the Pharmacy address.
     * @type {string}
     * @memberof CreatePharmacyRequest
     */
    address?: string;
}

/**
 * Check if a given object implements the CreatePharmacyRequest interface.
 */
export function instanceOfCreatePharmacyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreatePharmacyRequestFromJSON(json: any): CreatePharmacyRequest {
    return CreatePharmacyRequestFromJSONTyped(json, false);
}

export function CreatePharmacyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePharmacyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': json['patient_id'],
        'name': json['name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'faxNumber': !exists(json, 'fax_number') ? undefined : json['fax_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function CreatePharmacyRequestToJSON(value?: CreatePharmacyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'name': value.name,
        'phone_number': value.phoneNumber,
        'fax_number': value.faxNumber,
        'address': value.address,
    };
}

