/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEpisodeTask
 */
export interface CreateEpisodeTask {
    /**
     * Required. task_type represents the type of Task to be created.
     * @type {string}
     * @memberof CreateEpisodeTask
     */
    taskType: string;
    /**
     * Required. task represents the description or the content of the
     * task.
     * @type {string}
     * @memberof CreateEpisodeTask
     */
    task: string;
    /**
     * status represents the initial status of the Task, if empty, the default
     * is "TASK_STATUS_PENDING".
     * @type {string}
     * @memberof CreateEpisodeTask
     */
    status?: string;
}

/**
 * Check if a given object implements the CreateEpisodeTask interface.
 */
export function instanceOfCreateEpisodeTask(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskType" in value;
    isInstance = isInstance && "task" in value;

    return isInstance;
}

export function CreateEpisodeTaskFromJSON(json: any): CreateEpisodeTask {
    return CreateEpisodeTaskFromJSONTyped(json, false);
}

export function CreateEpisodeTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEpisodeTask {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskType': json['task_type'],
        'task': json['task'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function CreateEpisodeTaskToJSON(value?: CreateEpisodeTask | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_type': value.taskType,
        'task': value.task,
        'status': value.status,
    };
}

