/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEpisodeNote
 */
export interface CreateEpisodeNote {
    /**
     * Required. details represents the description or the content of the
     * Note.
     * @type {string}
     * @memberof CreateEpisodeNote
     */
    details: string;
    /**
     * Required. note_kind represents the type of the note, whether it is a
     * general note, a daily update, etc.
     * @type {string}
     * @memberof CreateEpisodeNote
     */
    noteKind: string;
}

/**
 * Check if a given object implements the CreateEpisodeNote interface.
 */
export function instanceOfCreateEpisodeNote(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "details" in value;
    isInstance = isInstance && "noteKind" in value;

    return isInstance;
}

export function CreateEpisodeNoteFromJSON(json: any): CreateEpisodeNote {
    return CreateEpisodeNoteFromJSONTyped(json, false);
}

export function CreateEpisodeNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEpisodeNote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'details': json['details'],
        'noteKind': json['note_kind'],
    };
}

export function CreateEpisodeNoteToJSON(value?: CreateEpisodeNote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'details': value.details,
        'note_kind': value.noteKind,
    };
}

