/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTemplateTask
 */
export interface CreateTemplateTask {
    /**
     * body is the description of the task in the template
     * @type {string}
     * @memberof CreateTemplateTask
     */
    body: string;
    /**
     * task_type_id is the type of the task in the template.
     * @type {string}
     * @memberof CreateTemplateTask
     */
    taskTypeId: string;
}

/**
 * Check if a given object implements the CreateTemplateTask interface.
 */
export function instanceOfCreateTemplateTask(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "body" in value;
    isInstance = isInstance && "taskTypeId" in value;

    return isInstance;
}

export function CreateTemplateTaskFromJSON(json: any): CreateTemplateTask {
    return CreateTemplateTaskFromJSONTyped(json, false);
}

export function CreateTemplateTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTemplateTask {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': json['body'],
        'taskTypeId': json['task_type_id'],
    };
}

export function CreateTemplateTaskToJSON(value?: CreateTemplateTask | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
        'task_type_id': value.taskTypeId,
    };
}

