/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExternalCareProvider } from './ExternalCareProvider';
import {
    ExternalCareProviderFromJSON,
    ExternalCareProviderFromJSONTyped,
    ExternalCareProviderToJSON,
} from './ExternalCareProvider';

/**
 * 
 * @export
 * @interface DeleteExternalCareProviderResponse
 */
export interface DeleteExternalCareProviderResponse {
    /**
     * patient_external_care_providers is the list of providers associated
     * with patient whose ExternalCareProvider was just deleted.
     * @type {Array<ExternalCareProvider>}
     * @memberof DeleteExternalCareProviderResponse
     */
    patientExternalCareProviders?: Array<ExternalCareProvider>;
}

/**
 * Check if a given object implements the DeleteExternalCareProviderResponse interface.
 */
export function instanceOfDeleteExternalCareProviderResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteExternalCareProviderResponseFromJSON(json: any): DeleteExternalCareProviderResponse {
    return DeleteExternalCareProviderResponseFromJSONTyped(json, false);
}

export function DeleteExternalCareProviderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteExternalCareProviderResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientExternalCareProviders': !exists(json, 'patient_external_care_providers') ? undefined : ((json['patient_external_care_providers'] as Array<any>).map(ExternalCareProviderFromJSON)),
    };
}

export function DeleteExternalCareProviderResponseToJSON(value?: DeleteExternalCareProviderResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_external_care_providers': value.patientExternalCareProviders === undefined ? undefined : ((value.patientExternalCareProviders as Array<any>).map(ExternalCareProviderToJSON)),
    };
}

