/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DuplicateEpisodeLatestVisitResponse
 */
export interface DuplicateEpisodeLatestVisitResponse {
    /**
     * care_request_id represents the ID of the duplicated Care Request.
     * @type {string}
     * @memberof DuplicateEpisodeLatestVisitResponse
     */
    careRequestId: string;
}

/**
 * Check if a given object implements the DuplicateEpisodeLatestVisitResponse interface.
 */
export function instanceOfDuplicateEpisodeLatestVisitResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "careRequestId" in value;

    return isInstance;
}

export function DuplicateEpisodeLatestVisitResponseFromJSON(json: any): DuplicateEpisodeLatestVisitResponse {
    return DuplicateEpisodeLatestVisitResponseFromJSONTyped(json, false);
}

export function DuplicateEpisodeLatestVisitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DuplicateEpisodeLatestVisitResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'careRequestId': json['care_request_id'],
    };
}

export function DuplicateEpisodeLatestVisitResponseToJSON(value?: DuplicateEpisodeLatestVisitResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'care_request_id': value.careRequestId,
    };
}

