/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EHRAppointment
 */
export interface EHRAppointment {
    /**
     * place_of_service represents the athena appointment department.
     * @type {string}
     * @memberof EHRAppointment
     */
    placeOfService?: string;
    /**
     * athena appointment type.
     * @type {string}
     * @memberof EHRAppointment
     */
    appointmentType?: string;
    /**
     * appointment date. Expected format: 'm/d/Y'.
     * @type {string}
     * @memberof EHRAppointment
     */
    date?: string;
    /**
     * appointment start time. Expected format: 'H:m'.
     * @type {string}
     * @memberof EHRAppointment
     */
    startTime?: string;
}

/**
 * Check if a given object implements the EHRAppointment interface.
 */
export function instanceOfEHRAppointment(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EHRAppointmentFromJSON(json: any): EHRAppointment {
    return EHRAppointmentFromJSONTyped(json, false);
}

export function EHRAppointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EHRAppointment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'placeOfService': !exists(json, 'place_of_service') ? undefined : json['place_of_service'],
        'appointmentType': !exists(json, 'appointment_type') ? undefined : json['appointment_type'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'startTime': !exists(json, 'start_time') ? undefined : json['start_time'],
    };
}

export function EHRAppointmentToJSON(value?: EHRAppointment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'place_of_service': value.placeOfService,
        'appointment_type': value.appointmentType,
        'date': value.date,
        'start_time': value.startTime,
    };
}

