/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VisitListElement } from './VisitListElement';
import {
    VisitListElementFromJSON,
    VisitListElementFromJSONTyped,
    VisitListElementToJSON,
} from './VisitListElement';

/**
 * 
 * @export
 * @interface GetEpisodeVisitsResponse
 */
export interface GetEpisodeVisitsResponse {
    /**
     * visits represents the list of Visits associated to the given Episode ID.
     * @type {Array<VisitListElement>}
     * @memberof GetEpisodeVisitsResponse
     */
    visits?: Array<VisitListElement>;
}

/**
 * Check if a given object implements the GetEpisodeVisitsResponse interface.
 */
export function instanceOfGetEpisodeVisitsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetEpisodeVisitsResponseFromJSON(json: any): GetEpisodeVisitsResponse {
    return GetEpisodeVisitsResponseFromJSONTyped(json, false);
}

export function GetEpisodeVisitsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEpisodeVisitsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'visits': !exists(json, 'visits') ? undefined : ((json['visits'] as Array<any>).map(VisitListElementFromJSON)),
    };
}

export function GetEpisodeVisitsResponseToJSON(value?: GetEpisodeVisitsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'visits': value.visits === undefined ? undefined : ((value.visits as Array<any>).map(VisitListElementToJSON)),
    };
}

