/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProviderType } from './ProviderType';
import {
    ProviderTypeFromJSON,
    ProviderTypeFromJSONTyped,
    ProviderTypeToJSON,
} from './ProviderType';

/**
 * 
 * @export
 * @interface GetProviderTypesResponse
 */
export interface GetProviderTypesResponse {
    /**
     * provider_types represents the list of all ProviderTypes in the catalog.
     * @type {Array<ProviderType>}
     * @memberof GetProviderTypesResponse
     */
    providerTypes?: Array<ProviderType>;
}

/**
 * Check if a given object implements the GetProviderTypesResponse interface.
 */
export function instanceOfGetProviderTypesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetProviderTypesResponseFromJSON(json: any): GetProviderTypesResponse {
    return GetProviderTypesResponseFromJSONTyped(json, false);
}

export function GetProviderTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProviderTypesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'providerTypes': !exists(json, 'provider_types') ? undefined : ((json['provider_types'] as Array<any>).map(ProviderTypeFromJSON)),
    };
}

export function GetProviderTypesResponseToJSON(value?: GetProviderTypesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider_types': value.providerTypes === undefined ? undefined : ((value.providerTypes as Array<any>).map(ProviderTypeToJSON)),
    };
}

