/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { Patient } from './Patient';
import {
    PatientFromJSON,
    PatientFromJSONTyped,
    PatientToJSON,
} from './Patient';

/**
 * 
 * @export
 * @interface GetPatientsResponse
 */
export interface GetPatientsResponse {
    /**
     * patients represents the collection of Patients corresponding to the page
     * and filters requested.
     * @type {Array<Patient>}
     * @memberof GetPatientsResponse
     */
    patients: Array<Patient>;
    /**
     * 
     * @type {PageInfo}
     * @memberof GetPatientsResponse
     */
    meta?: PageInfo;
}

/**
 * Check if a given object implements the GetPatientsResponse interface.
 */
export function instanceOfGetPatientsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "patients" in value;

    return isInstance;
}

export function GetPatientsResponseFromJSON(json: any): GetPatientsResponse {
    return GetPatientsResponseFromJSONTyped(json, false);
}

export function GetPatientsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPatientsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patients': ((json['patients'] as Array<any>).map(PatientFromJSON)),
        'meta': !exists(json, 'meta') ? undefined : PageInfoFromJSON(json['meta']),
    };
}

export function GetPatientsResponseToJSON(value?: GetPatientsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patients': ((value.patients as Array<any>).map(PatientToJSON)),
        'meta': PageInfoToJSON(value.meta),
    };
}

