/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Note } from './Note';
import {
    NoteFromJSON,
    NoteFromJSONTyped,
    NoteToJSON,
} from './Note';

/**
 * 
 * @export
 * @interface GetServiceRequestNotesResponse
 */
export interface GetServiceRequestNotesResponse {
    /**
     * notes is a collection of Note entities.
     * @type {Array<Note>}
     * @memberof GetServiceRequestNotesResponse
     */
    notes: Array<Note>;
}

/**
 * Check if a given object implements the GetServiceRequestNotesResponse interface.
 */
export function instanceOfGetServiceRequestNotesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "notes" in value;

    return isInstance;
}

export function GetServiceRequestNotesResponseFromJSON(json: any): GetServiceRequestNotesResponse {
    return GetServiceRequestNotesResponseFromJSONTyped(json, false);
}

export function GetServiceRequestNotesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServiceRequestNotesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notes': ((json['notes'] as Array<any>).map(NoteFromJSON)),
    };
}

export function GetServiceRequestNotesResponseToJSON(value?: GetServiceRequestNotesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notes': ((value.notes as Array<any>).map(NoteToJSON)),
    };
}

