/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ServiceRequestStatus } from './ServiceRequestStatus';
import {
    ServiceRequestStatusFromJSON,
    ServiceRequestStatusFromJSONTyped,
    ServiceRequestStatusToJSON,
} from './ServiceRequestStatus';

/**
 * 
 * @export
 * @interface GetServiceRequestStatusResponse
 */
export interface GetServiceRequestStatusResponse {
    /**
     * service_request_status represents a collection of ServiceRequestStatus.
     * @type {Array<ServiceRequestStatus>}
     * @memberof GetServiceRequestStatusResponse
     */
    serviceRequestStatus: Array<ServiceRequestStatus>;
}

/**
 * Check if a given object implements the GetServiceRequestStatusResponse interface.
 */
export function instanceOfGetServiceRequestStatusResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "serviceRequestStatus" in value;

    return isInstance;
}

export function GetServiceRequestStatusResponseFromJSON(json: any): GetServiceRequestStatusResponse {
    return GetServiceRequestStatusResponseFromJSONTyped(json, false);
}

export function GetServiceRequestStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServiceRequestStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serviceRequestStatus': ((json['service_request_status'] as Array<any>).map(ServiceRequestStatusFromJSON)),
    };
}

export function GetServiceRequestStatusResponseToJSON(value?: GetServiceRequestStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'service_request_status': ((value.serviceRequestStatus as Array<any>).map(ServiceRequestStatusToJSON)),
    };
}

