/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { ServiceRequestListElement } from './ServiceRequestListElement';
import {
    ServiceRequestListElementFromJSON,
    ServiceRequestListElementFromJSONTyped,
    ServiceRequestListElementToJSON,
} from './ServiceRequestListElement';

/**
 * 
 * @export
 * @interface GetServiceRequestsResponse
 */
export interface GetServiceRequestsResponse {
    /**
     * service_requests represents the collection of ServiceRequestListElement
     * corresponding to the requested page and filters.
     * @type {Array<ServiceRequestListElement>}
     * @memberof GetServiceRequestsResponse
     */
    serviceRequests: Array<ServiceRequestListElement>;
    /**
     * 
     * @type {PageInfo}
     * @memberof GetServiceRequestsResponse
     */
    meta?: PageInfo;
}

/**
 * Check if a given object implements the GetServiceRequestsResponse interface.
 */
export function instanceOfGetServiceRequestsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "serviceRequests" in value;

    return isInstance;
}

export function GetServiceRequestsResponseFromJSON(json: any): GetServiceRequestsResponse {
    return GetServiceRequestsResponseFromJSONTyped(json, false);
}

export function GetServiceRequestsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServiceRequestsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serviceRequests': ((json['service_requests'] as Array<any>).map(ServiceRequestListElementFromJSON)),
        'meta': !exists(json, 'meta') ? undefined : PageInfoFromJSON(json['meta']),
    };
}

export function GetServiceRequestsResponseToJSON(value?: GetServiceRequestsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'service_requests': ((value.serviceRequests as Array<any>).map(ServiceRequestListElementToJSON)),
        'meta': PageInfoToJSON(value.meta),
    };
}

