/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { TaskTemplate } from './TaskTemplate';
import {
    TaskTemplateFromJSON,
    TaskTemplateFromJSONTyped,
    TaskTemplateToJSON,
} from './TaskTemplate';

/**
 * 
 * @export
 * @interface GetTaskTemplatesResponse
 */
export interface GetTaskTemplatesResponse {
    /**
     * task_templates represents the task templates elements retrieved.
     * @type {Array<TaskTemplate>}
     * @memberof GetTaskTemplatesResponse
     */
    taskTemplates: Array<TaskTemplate>;
    /**
     * 
     * @type {PageInfo}
     * @memberof GetTaskTemplatesResponse
     */
    meta?: PageInfo;
}

/**
 * Check if a given object implements the GetTaskTemplatesResponse interface.
 */
export function instanceOfGetTaskTemplatesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskTemplates" in value;

    return isInstance;
}

export function GetTaskTemplatesResponseFromJSON(json: any): GetTaskTemplatesResponse {
    return GetTaskTemplatesResponseFromJSONTyped(json, false);
}

export function GetTaskTemplatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTaskTemplatesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskTemplates': ((json['task_templates'] as Array<any>).map(TaskTemplateFromJSON)),
        'meta': !exists(json, 'meta') ? undefined : PageInfoFromJSON(json['meta']),
    };
}

export function GetTaskTemplatesResponseToJSON(value?: GetTaskTemplatesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_templates': ((value.taskTemplates as Array<any>).map(TaskTemplateToJSON)),
        'meta': PageInfoToJSON(value.meta),
    };
}

