/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface GetUsersByIDResponse
 */
export interface GetUsersByIDResponse {
    /**
     * users represents the list of instances of the requested Users.
     * @type {Array<User>}
     * @memberof GetUsersByIDResponse
     */
    users: Array<User>;
}

/**
 * Check if a given object implements the GetUsersByIDResponse interface.
 */
export function instanceOfGetUsersByIDResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function GetUsersByIDResponseFromJSON(json: any): GetUsersByIDResponse {
    return GetUsersByIDResponseFromJSONTyped(json, false);
}

export function GetUsersByIDResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsersByIDResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(UserFromJSON)),
    };
}

export function GetUsersByIDResponseToJSON(value?: GetUsersByIDResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': ((value.users as Array<any>).map(UserToJSON)),
    };
}

