/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DateAvailability } from './DateAvailability';
import {
    DateAvailabilityFromJSON,
    DateAvailabilityFromJSONTyped,
    DateAvailabilityToJSON,
} from './DateAvailability';

/**
 * 
 * @export
 * @interface GetVisitAvailabilityResponse
 */
export interface GetVisitAvailabilityResponse {
    /**
     * availability represents a list of dates along with
     * their corresponding availability.
     * @type {Array<DateAvailability>}
     * @memberof GetVisitAvailabilityResponse
     */
    availability?: Array<DateAvailability>;
}

/**
 * Check if a given object implements the GetVisitAvailabilityResponse interface.
 */
export function instanceOfGetVisitAvailabilityResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetVisitAvailabilityResponseFromJSON(json: any): GetVisitAvailabilityResponse {
    return GetVisitAvailabilityResponseFromJSONTyped(json, false);
}

export function GetVisitAvailabilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVisitAvailabilityResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availability': !exists(json, 'availability') ? undefined : ((json['availability'] as Array<any>).map(DateAvailabilityFromJSON)),
    };
}

export function GetVisitAvailabilityResponseToJSON(value?: GetVisitAvailabilityResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availability': value.availability === undefined ? undefined : ((value.availability as Array<any>).map(DateAvailabilityToJSON)),
    };
}

