/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VisitType } from './VisitType';
import {
    VisitTypeFromJSON,
    VisitTypeFromJSONTyped,
    VisitTypeToJSON,
} from './VisitType';

/**
 * 
 * @export
 * @interface GetVisitTypesResponse
 */
export interface GetVisitTypesResponse {
    /**
     * visit_types represents the list of all VisitTypes.
     * @type {Array<VisitType>}
     * @memberof GetVisitTypesResponse
     */
    visitTypes: Array<VisitType>;
}

/**
 * Check if a given object implements the GetVisitTypesResponse interface.
 */
export function instanceOfGetVisitTypesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "visitTypes" in value;

    return isInstance;
}

export function GetVisitTypesResponseFromJSON(json: any): GetVisitTypesResponse {
    return GetVisitTypesResponseFromJSONTyped(json, false);
}

export function GetVisitTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVisitTypesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'visitTypes': ((json['visit_types'] as Array<any>).map(VisitTypeFromJSON)),
    };
}

export function GetVisitTypesResponseToJSON(value?: GetVisitTypesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'visit_types': ((value.visitTypes as Array<any>).map(VisitTypeToJSON)),
    };
}

