/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetVisitAvailabilityRequest
 */
export interface GetVisitAvailabilityRequest {
    /**
     * Required. care_request_id represents the ID of the Care Request instance
     * to get its availability.
     * @type {string}
     * @memberof GetVisitAvailabilityRequest
     */
    careRequestId: string;
    /**
     * requested_dates is the list of dates to get the availability.
     * in the format MM-DD-YYYY.
     * @type {Array<string>}
     * @memberof GetVisitAvailabilityRequest
     */
    requestedDates?: Array<string>;
}

/**
 * Check if a given object implements the GetVisitAvailabilityRequest interface.
 */
export function instanceOfGetVisitAvailabilityRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "careRequestId" in value;

    return isInstance;
}

export function GetVisitAvailabilityRequestFromJSON(json: any): GetVisitAvailabilityRequest {
    return GetVisitAvailabilityRequestFromJSONTyped(json, false);
}

export function GetVisitAvailabilityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVisitAvailabilityRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'careRequestId': json['care_request_id'],
        'requestedDates': !exists(json, 'requested_dates') ? undefined : json['requested_dates'],
    };
}

export function GetVisitAvailabilityRequestToJSON(value?: GetVisitAvailabilityRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'care_request_id': value.careRequestId,
        'requested_dates': value.requestedDates,
    };
}

