/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Insurance
 */
export interface Insurance {
    /**
     * id represents the unique identifier of the Insurance.
     * @type {string}
     * @memberof Insurance
     */
    id: string;
    /**
     * name represents the name of the Insurance.
     * @type {string}
     * @memberof Insurance
     */
    name: string;
    /**
     * member_id represents the external member_id value of the Insurance, most
     * likely managed by each insurance company.
     * @type {string}
     * @memberof Insurance
     */
    memberId?: string;
    /**
     * priority represents priority value for the Insurance, this is helpful for
     * knowing which insurance in the list is the primary one, secondary, etc.
     * @type {number}
     * @memberof Insurance
     */
    priority: number;
    /**
     * patient_id represents the id for the patient this Insurance is associated
     * with.
     * @type {string}
     * @memberof Insurance
     */
    patientId: string;
}

/**
 * Check if a given object implements the Insurance interface.
 */
export function instanceOfInsurance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "priority" in value;
    isInstance = isInstance && "patientId" in value;

    return isInstance;
}

export function InsuranceFromJSON(json: any): Insurance {
    return InsuranceFromJSONTyped(json, false);
}

export function InsuranceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Insurance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'memberId': !exists(json, 'member_id') ? undefined : json['member_id'],
        'priority': json['priority'],
        'patientId': json['patient_id'],
    };
}

export function InsuranceToJSON(value?: Insurance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'member_id': value.memberId,
        'priority': value.priority,
        'patient_id': value.patientId,
    };
}

