/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Car } from './Car';
import {
    CarFromJSON,
    CarFromJSONTyped,
    CarToJSON,
} from './Car';

/**
 * 
 * @export
 * @interface ListCarsByIDsResponse
 */
export interface ListCarsByIDsResponse {
    /**
     * cars represents the list of Cars.
     * @type {Array<Car>}
     * @memberof ListCarsByIDsResponse
     */
    cars: Array<Car>;
}

/**
 * Check if a given object implements the ListCarsByIDsResponse interface.
 */
export function instanceOfListCarsByIDsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cars" in value;

    return isInstance;
}

export function ListCarsByIDsResponseFromJSON(json: any): ListCarsByIDsResponse {
    return ListCarsByIDsResponseFromJSONTyped(json, false);
}

export function ListCarsByIDsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCarsByIDsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cars': ((json['cars'] as Array<any>).map(CarFromJSON)),
    };
}

export function ListCarsByIDsResponseToJSON(value?: ListCarsByIDsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cars': ((value.cars as Array<any>).map(CarToJSON)),
    };
}

