/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedicalDecisionMaker
 */
export interface MedicalDecisionMaker {
    /**
     * id represents the unique identifier of the MedicalDecisionMaker.
     * @type {string}
     * @memberof MedicalDecisionMaker
     */
    id: string;
    /**
     * first_name represents the first name of the MedicalDecisionMaker.
     * @type {string}
     * @memberof MedicalDecisionMaker
     */
    firstName: string;
    /**
     * last_name represents the last name of the MedicalDecisionMaker.
     * @type {string}
     * @memberof MedicalDecisionMaker
     */
    lastName: string;
    /**
     * phone_number represents the phone number of the MedicalDecisionMaker.
     * @type {string}
     * @memberof MedicalDecisionMaker
     */
    phoneNumber: string;
    /**
     * address represents the full string representation of the
     * MedicalDecisionMaker address.
     * @type {string}
     * @memberof MedicalDecisionMaker
     */
    address?: string;
    /**
     * relationship represents the relation the MedicalDecisionMaker has with the
     * patient it is assigned to, like "parent", "tutor", etc.
     * @type {string}
     * @memberof MedicalDecisionMaker
     */
    relationship: string;
    /**
     * patient_id represents the id for the patient this MedicalDecisionMaker is
     * associated with.
     * @type {string}
     * @memberof MedicalDecisionMaker
     */
    patientId: string;
}

/**
 * Check if a given object implements the MedicalDecisionMaker interface.
 */
export function instanceOfMedicalDecisionMaker(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "phoneNumber" in value;
    isInstance = isInstance && "relationship" in value;
    isInstance = isInstance && "patientId" in value;

    return isInstance;
}

export function MedicalDecisionMakerFromJSON(json: any): MedicalDecisionMaker {
    return MedicalDecisionMakerFromJSONTyped(json, false);
}

export function MedicalDecisionMakerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicalDecisionMaker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'phoneNumber': json['phone_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'relationship': json['relationship'],
        'patientId': json['patient_id'],
    };
}

export function MedicalDecisionMakerToJSON(value?: MedicalDecisionMaker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'phone_number': value.phoneNumber,
        'address': value.address,
        'relationship': value.relationship,
        'patient_id': value.patientId,
    };
}

