/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
    /**
     * page_size represents the amount of elements retrieved in the current page.
     * @type {string}
     * @memberof PageInfo
     */
    pageSize: string;
    /**
     * total_results represents the total amount of elements of the current list.
     * @type {string}
     * @memberof PageInfo
     */
    totalResults: string;
    /**
     * total_pages represents the total amount of pages for the current list
     * (total_results / page_size).
     * @type {string}
     * @memberof PageInfo
     */
    totalPages: string;
    /**
     * current_page represents number of the current page.
     * @type {string}
     * @memberof PageInfo
     */
    currentPage: string;
    /**
     * first_page represents a flag that indicates if the current page is the
     * first page.
     * @type {boolean}
     * @memberof PageInfo
     */
    firstPage?: boolean;
    /**
     * last_page represents a flag that indicates if the current page is the
     * last page.
     * @type {boolean}
     * @memberof PageInfo
     */
    lastPage?: boolean;
    /**
     * previous_page represents the number of the previous page, empty if the
     * current page is the first page.
     * @type {string}
     * @memberof PageInfo
     */
    previousPage?: string;
    /**
     * next_page represents the number of the next page, empty if the current page
     * is the last page
     * @type {string}
     * @memberof PageInfo
     */
    nextPage?: string;
}

/**
 * Check if a given object implements the PageInfo interface.
 */
export function instanceOfPageInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalResults" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "currentPage" in value;

    return isInstance;
}

export function PageInfoFromJSON(json: any): PageInfo {
    return PageInfoFromJSONTyped(json, false);
}

export function PageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pageSize': json['page_size'],
        'totalResults': json['total_results'],
        'totalPages': json['total_pages'],
        'currentPage': json['current_page'],
        'firstPage': !exists(json, 'first_page') ? undefined : json['first_page'],
        'lastPage': !exists(json, 'last_page') ? undefined : json['last_page'],
        'previousPage': !exists(json, 'previous_page') ? undefined : json['previous_page'],
        'nextPage': !exists(json, 'next_page') ? undefined : json['next_page'],
    };
}

export function PageInfoToJSON(value?: PageInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page_size': value.pageSize,
        'total_results': value.totalResults,
        'total_pages': value.totalPages,
        'current_page': value.currentPage,
        'first_page': value.firstPage,
        'last_page': value.lastPage,
        'previous_page': value.previousPage,
        'next_page': value.nextPage,
    };
}

