/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Pharmacy
 */
export interface Pharmacy {
    /**
     * id represents the unique identifier of the Pharmacy.
     * @type {string}
     * @memberof Pharmacy
     */
    id: string;
    /**
     * name represents the name of the Pharmacy.
     * @type {string}
     * @memberof Pharmacy
     */
    name: string;
    /**
     * phone_number represents the phone number of the Pharmacy.
     * @type {string}
     * @memberof Pharmacy
     */
    phoneNumber?: string;
    /**
     * fax_number represents the fax number of the Pharmacy.
     * @type {string}
     * @memberof Pharmacy
     */
    faxNumber?: string;
    /**
     * address represents the full string representation of the Pharmacy address.
     * @type {string}
     * @memberof Pharmacy
     */
    address?: string;
    /**
     * patient_id represents the id for the patient this Pharmacy is associated
     * with.
     * @type {string}
     * @memberof Pharmacy
     */
    patientId: string;
}

/**
 * Check if a given object implements the Pharmacy interface.
 */
export function instanceOfPharmacy(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "patientId" in value;

    return isInstance;
}

export function PharmacyFromJSON(json: any): Pharmacy {
    return PharmacyFromJSONTyped(json, false);
}

export function PharmacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pharmacy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'faxNumber': !exists(json, 'fax_number') ? undefined : json['fax_number'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'patientId': json['patient_id'],
    };
}

export function PharmacyToJSON(value?: Pharmacy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'phone_number': value.phoneNumber,
        'fax_number': value.faxNumber,
        'address': value.address,
        'patient_id': value.patientId,
    };
}

