/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderType
 */
export interface ProviderType {
    /**
     * id represents the unique identifier of the ProviderType.
     * @type {string}
     * @memberof ProviderType
     */
    id: string;
    /**
     * name represents the name of the ProviderType.
     * @type {string}
     * @memberof ProviderType
     */
    name: string;
}

/**
 * Check if a given object implements the ProviderType interface.
 */
export function instanceOfProviderType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProviderTypeFromJSON(json: any): ProviderType {
    return ProviderTypeFromJSONTyped(json, false);
}

export function ProviderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ProviderTypeToJSON(value?: ProviderType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

