/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TimeOfDay } from './TimeOfDay';
import {
    TimeOfDayFromJSON,
    TimeOfDayFromJSONTyped,
    TimeOfDayToJSON,
} from './TimeOfDay';

/**
 * Represents a day of the week, along with open and close times.
 * Usually used to represent a Market open and close times.
 * @export
 * @interface ScheduleDay
 */
export interface ScheduleDay {
    /**
     * Day of week
     * Sunday = 0, Monday = 1 ...
     * @type {number}
     * @memberof ScheduleDay
     */
    dayOfWeek?: number;
    /**
     * 
     * @type {TimeOfDay}
     * @memberof ScheduleDay
     */
    openTime?: TimeOfDay;
    /**
     * 
     * @type {TimeOfDay}
     * @memberof ScheduleDay
     */
    closeTime?: TimeOfDay;
}

/**
 * Check if a given object implements the ScheduleDay interface.
 */
export function instanceOfScheduleDay(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScheduleDayFromJSON(json: any): ScheduleDay {
    return ScheduleDayFromJSONTyped(json, false);
}

export function ScheduleDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleDay {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dayOfWeek': !exists(json, 'day_of_week') ? undefined : json['day_of_week'],
        'openTime': !exists(json, 'open_time') ? undefined : TimeOfDayFromJSON(json['open_time']),
        'closeTime': !exists(json, 'close_time') ? undefined : TimeOfDayFromJSON(json['close_time']),
    };
}

export function ScheduleDayToJSON(value?: ScheduleDay | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'day_of_week': value.dayOfWeek,
        'open_time': TimeOfDayToJSON(value.openTime),
        'close_time': TimeOfDayToJSON(value.closeTime),
    };
}

