/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleVisitRequest
 */
export interface ScheduleVisitRequest {
    /**
     * care_request_id represents the ID of the Care Request to be scheduled.
     * @type {string}
     * @memberof ScheduleVisitRequest
     */
    careRequestId?: string;
    /**
     * patient_availability_start_time represents the start time of the patient's
     * availability in Unix format
     * @type {string}
     * @memberof ScheduleVisitRequest
     */
    patientAvailabilityStartTime?: string;
    /**
     * patient_availability_end_time represents the end time of the patient's
     * availability in Unix format
     * @type {string}
     * @memberof ScheduleVisitRequest
     */
    patientAvailabilityEndTime?: string;
    /**
     * episode_id represents the id of the Episode where the Visit should be saved
     * upon scheduling.
     * @type {string}
     * @memberof ScheduleVisitRequest
     */
    episodeId?: string;
}

/**
 * Check if a given object implements the ScheduleVisitRequest interface.
 */
export function instanceOfScheduleVisitRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScheduleVisitRequestFromJSON(json: any): ScheduleVisitRequest {
    return ScheduleVisitRequestFromJSONTyped(json, false);
}

export function ScheduleVisitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleVisitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'careRequestId': !exists(json, 'care_request_id') ? undefined : json['care_request_id'],
        'patientAvailabilityStartTime': !exists(json, 'patient_availability_start_time') ? undefined : json['patient_availability_start_time'],
        'patientAvailabilityEndTime': !exists(json, 'patient_availability_end_time') ? undefined : json['patient_availability_end_time'],
        'episodeId': !exists(json, 'episode_id') ? undefined : json['episode_id'],
    };
}

export function ScheduleVisitRequestToJSON(value?: ScheduleVisitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'care_request_id': value.careRequestId,
        'patient_availability_start_time': value.patientAvailabilityStartTime,
        'patient_availability_end_time': value.patientAvailabilityEndTime,
        'episode_id': value.episodeId,
    };
}

