/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceRequestStatus
 */
export interface ServiceRequestStatus {
    /**
     * id represents the unique identifier of the ServiceRequest.
     * @type {string}
     * @memberof ServiceRequestStatus
     */
    id: string;
    /**
     * name is a string representation of the ServiceRequest.
     * @type {string}
     * @memberof ServiceRequestStatus
     */
    name: string;
    /**
     * is_active is a flag stating if a ServceRequest is stll active.
     * @type {boolean}
     * @memberof ServiceRequestStatus
     */
    isActive: boolean;
    /**
     * slug is a human and code friendly string representation of a
     * ServiceRequestStatus.
     * @type {string}
     * @memberof ServiceRequestStatus
     */
    slug: string;
}

/**
 * Check if a given object implements the ServiceRequestStatus interface.
 */
export function instanceOfServiceRequestStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "isActive" in value;
    isInstance = isInstance && "slug" in value;

    return isInstance;
}

export function ServiceRequestStatusFromJSON(json: any): ServiceRequestStatus {
    return ServiceRequestStatusFromJSONTyped(json, false);
}

export function ServiceRequestStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceRequestStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'isActive': json['is_active'],
        'slug': json['slug'],
    };
}

export function ServiceRequestStatusToJSON(value?: ServiceRequestStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'is_active': value.isActive,
        'slug': value.slug,
    };
}

