/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceLine
 */
export interface ServiceLine {
    /**
     * id represents the unique identifier of the Service Line.
     * @type {string}
     * @memberof ServiceLine
     */
    id: string;
    /**
     * name represents the name of the Service Line.
     * @type {string}
     * @memberof ServiceLine
     */
    name: string;
    /**
     * short_name represents the short version of the name of the Service Line.
     * @type {string}
     * @memberof ServiceLine
     */
    shortName: string;
}

/**
 * Check if a given object implements the ServiceLine interface.
 */
export function instanceOfServiceLine(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "shortName" in value;

    return isInstance;
}

export function ServiceLineFromJSON(json: any): ServiceLine {
    return ServiceLineFromJSONTyped(json, false);
}

export function ServiceLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceLine {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'shortName': json['short_name'],
    };
}

export function ServiceLineToJSON(value?: ServiceLine | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'short_name': value.shortName,
    };
}

