/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServiceRequestCategory = {
    Unspecified: 'SERVICE_REQUEST_CATEGORY_UNSPECIFIED',
    AdvancedCare: 'SERVICE_REQUEST_CATEGORY_ADVANCED_CARE'
} as const;
export type ServiceRequestCategory = typeof ServiceRequestCategory[keyof typeof ServiceRequestCategory];


export function ServiceRequestCategoryFromJSON(json: any): ServiceRequestCategory {
    return ServiceRequestCategoryFromJSONTyped(json, false);
}

export function ServiceRequestCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceRequestCategory {
    return json as ServiceRequestCategory;
}

export function ServiceRequestCategoryToJSON(value?: ServiceRequestCategory | null): any {
    return value as any;
}

