/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StationPatient
 */
export interface StationPatient {
    /**
     * id is the unique numeric identifier for a StationPatient
     * @type {string}
     * @memberof StationPatient
     */
    id: string;
    /**
     * first_name is a string representing the first name of the StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    firstName?: string;
    /**
     * last_name is a string representing the last name of the StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    lastName?: string;
    /**
     * ehr_id represents the electronic health record associated with the
     * StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    ehrId: string;
    /**
     * date_of_birth is the date the StationPatient was born at.
     * @type {string}
     * @memberof StationPatient
     */
    dateOfBirth: string;
    /**
     * sex represents the sex of the StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    sex?: string;
    /**
     * visits_in_past_90_days is the total number of visits that the
     * StationPatient had in the past 90 days
     * @type {number}
     * @memberof StationPatient
     */
    visitsInPast90Days: number;
    /**
     * has_been_in_advanced_care states if the StationPatient has been previously
     * in advanced care.
     * @type {boolean}
     * @memberof StationPatient
     */
    hasBeenInAdvancedCare: boolean;
    /**
     * id represents the unique numeric value of the insurance associated with the
     * StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    insurancePlanId?: string;
    /**
     * name is a string representation of the name of the insurance plan
     * associated with the StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    insurancePlanName?: string;
    /**
     * network represents the insurance network's name associated with the
     * StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    insuranceNetworkName?: string;
    /**
     * member_id represents the patient's member id for the insurance associated
     * with the StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    insuranceMemberId?: string;
    /**
     * phone_number represents the phone number of the StationPatient.
     * @type {string}
     * @memberof StationPatient
     */
    phoneNumber?: string;
}

/**
 * Check if a given object implements the StationPatient interface.
 */
export function instanceOfStationPatient(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "ehrId" in value;
    isInstance = isInstance && "dateOfBirth" in value;
    isInstance = isInstance && "visitsInPast90Days" in value;
    isInstance = isInstance && "hasBeenInAdvancedCare" in value;

    return isInstance;
}

export function StationPatientFromJSON(json: any): StationPatient {
    return StationPatientFromJSONTyped(json, false);
}

export function StationPatientFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationPatient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'ehrId': json['ehr_id'],
        'dateOfBirth': json['date_of_birth'],
        'sex': !exists(json, 'sex') ? undefined : json['sex'],
        'visitsInPast90Days': json['visits_in_past_90_days'],
        'hasBeenInAdvancedCare': json['has_been_in_advanced_care'],
        'insurancePlanId': !exists(json, 'insurance_plan_id') ? undefined : json['insurance_plan_id'],
        'insurancePlanName': !exists(json, 'insurance_plan_name') ? undefined : json['insurance_plan_name'],
        'insuranceNetworkName': !exists(json, 'insurance_network_name') ? undefined : json['insurance_network_name'],
        'insuranceMemberId': !exists(json, 'insurance_member_id') ? undefined : json['insurance_member_id'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
    };
}

export function StationPatientToJSON(value?: StationPatient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'ehr_id': value.ehrId,
        'date_of_birth': value.dateOfBirth,
        'sex': value.sex,
        'visits_in_past_90_days': value.visitsInPast90Days,
        'has_been_in_advanced_care': value.hasBeenInAdvancedCare,
        'insurance_plan_id': value.insurancePlanId,
        'insurance_plan_name': value.insurancePlanName,
        'insurance_network_name': value.insuranceNetworkName,
        'insurance_member_id': value.insuranceMemberId,
        'phone_number': value.phoneNumber,
    };
}

