/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StationCareRequestListElement
 */
export interface StationCareRequestListElement {
    /**
     * id is the unique numeric identifier for a StationCareRequest.
     * @type {string}
     * @memberof StationCareRequestListElement
     */
    id: string;
    /**
     * chief_complaint is a string describing the chief complaint of the
     * StationCareRequest.
     * @type {string}
     * @memberof StationCareRequestListElement
     */
    chiefComplaint: string;
}

/**
 * Check if a given object implements the StationCareRequestListElement interface.
 */
export function instanceOfStationCareRequestListElement(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "chiefComplaint" in value;

    return isInstance;
}

export function StationCareRequestListElementFromJSON(json: any): StationCareRequestListElement {
    return StationCareRequestListElementFromJSONTyped(json, false);
}

export function StationCareRequestListElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationCareRequestListElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'chiefComplaint': json['chief_complaint'],
    };
}

export function StationCareRequestListElementToJSON(value?: StationCareRequestListElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'chief_complaint': value.chiefComplaint,
    };
}

