/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeOfDay
 */
export interface TimeOfDay {
    /**
     * Hours of day in 24 hour format. Should be from 0 to 23. An API may choose
     * to allow the value "24:00:00" for scenarios like business closing time.
     * @type {number}
     * @memberof TimeOfDay
     */
    hours?: number;
    /**
     * Minutes of hour of day. Must be from 0 to 59.
     * @type {number}
     * @memberof TimeOfDay
     */
    minutes?: number;
    /**
     * Seconds of minutes of the time. Must normally be from 0 to 59. An API may
     * allow the value 60 if it allows leap-seconds.
     * @type {number}
     * @memberof TimeOfDay
     */
    seconds?: number;
    /**
     * Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.
     * @type {number}
     * @memberof TimeOfDay
     */
    nanos?: number;
}

/**
 * Check if a given object implements the TimeOfDay interface.
 */
export function instanceOfTimeOfDay(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TimeOfDayFromJSON(json: any): TimeOfDay {
    return TimeOfDayFromJSONTyped(json, false);
}

export function TimeOfDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeOfDay {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hours': !exists(json, 'hours') ? undefined : json['hours'],
        'minutes': !exists(json, 'minutes') ? undefined : json['minutes'],
        'seconds': !exists(json, 'seconds') ? undefined : json['seconds'],
        'nanos': !exists(json, 'nanos') ? undefined : json['nanos'],
    };
}

export function TimeOfDayToJSON(value?: TimeOfDay | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hours': value.hours,
        'minutes': value.minutes,
        'seconds': value.seconds,
        'nanos': value.nanos,
    };
}

