/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Insurance } from './Insurance';
import {
    InsuranceFromJSON,
    InsuranceFromJSONTyped,
    InsuranceToJSON,
} from './Insurance';

/**
 * 
 * @export
 * @interface UpdateInsuranceResponse
 */
export interface UpdateInsuranceResponse {
    /**
     * 
     * @type {Insurance}
     * @memberof UpdateInsuranceResponse
     */
    insurance?: Insurance;
    /**
     * patient_insurances is the list of Insurances associated to the Patient
     * whose Insurance was just updated. It is sorted by priority.
     * @type {Array<Insurance>}
     * @memberof UpdateInsuranceResponse
     */
    patientInsurances?: Array<Insurance>;
}

/**
 * Check if a given object implements the UpdateInsuranceResponse interface.
 */
export function instanceOfUpdateInsuranceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateInsuranceResponseFromJSON(json: any): UpdateInsuranceResponse {
    return UpdateInsuranceResponseFromJSONTyped(json, false);
}

export function UpdateInsuranceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateInsuranceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'insurance': !exists(json, 'insurance') ? undefined : InsuranceFromJSON(json['insurance']),
        'patientInsurances': !exists(json, 'patient_insurances') ? undefined : ((json['patient_insurances'] as Array<any>).map(InsuranceFromJSON)),
    };
}

export function UpdateInsuranceResponseToJSON(value?: UpdateInsuranceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'insurance': InsuranceToJSON(value.insurance),
        'patient_insurances': value.patientInsurances === undefined ? undefined : ((value.patientInsurances as Array<any>).map(InsuranceToJSON)),
    };
}

