/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskTemplate } from './TaskTemplate';
import {
    TaskTemplateFromJSON,
    TaskTemplateFromJSONTyped,
    TaskTemplateToJSON,
} from './TaskTemplate';

/**
 * 
 * @export
 * @interface UpdateTaskTemplateResponse
 */
export interface UpdateTaskTemplateResponse {
    /**
     * 
     * @type {TaskTemplate}
     * @memberof UpdateTaskTemplateResponse
     */
    taskTemplate?: TaskTemplate;
}

/**
 * Check if a given object implements the UpdateTaskTemplateResponse interface.
 */
export function instanceOfUpdateTaskTemplateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateTaskTemplateResponseFromJSON(json: any): UpdateTaskTemplateResponse {
    return UpdateTaskTemplateResponseFromJSONTyped(json, false);
}

export function UpdateTaskTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskTemplateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskTemplate': !exists(json, 'task_template') ? undefined : TaskTemplateFromJSON(json['task_template']),
    };
}

export function UpdateTaskTemplateResponseToJSON(value?: UpdateTaskTemplateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_template': TaskTemplateToJSON(value.taskTemplate),
    };
}

