/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaskTemplateTask
 */
export interface UpdateTaskTemplateTask {
    /**
     * body is the description of the task in the template
     * @type {string}
     * @memberof UpdateTaskTemplateTask
     */
    body?: string;
    /**
     * task_type_id is the type of the task in the template.
     * @type {string}
     * @memberof UpdateTaskTemplateTask
     */
    taskTypeId?: string;
    /**
     * id represents the unique identifier of the Task.
     * @type {string}
     * @memberof UpdateTaskTemplateTask
     */
    id?: string;
    /**
     * destroy represents if the Task should be deleted.
     * @type {boolean}
     * @memberof UpdateTaskTemplateTask
     */
    destroy?: boolean;
}

/**
 * Check if a given object implements the UpdateTaskTemplateTask interface.
 */
export function instanceOfUpdateTaskTemplateTask(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateTaskTemplateTaskFromJSON(json: any): UpdateTaskTemplateTask {
    return UpdateTaskTemplateTaskFromJSONTyped(json, false);
}

export function UpdateTaskTemplateTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskTemplateTask {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': !exists(json, 'body') ? undefined : json['body'],
        'taskTypeId': !exists(json, 'task_type_id') ? undefined : json['task_type_id'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'destroy': !exists(json, 'destroy') ? undefined : json['destroy'],
    };
}

export function UpdateTaskTemplateTaskToJSON(value?: UpdateTaskTemplateTask | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
        'task_type_id': value.taskTypeId,
        'id': value.id,
        'destroy': value.destroy,
    };
}

