/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UpdateVisitStatusOption = {
    Unspecified: 'UPDATE_VISIT_STATUS_OPTION_UNSPECIFIED',
    OnRoute: 'UPDATE_VISIT_STATUS_OPTION_ON_ROUTE',
    OnScene: 'UPDATE_VISIT_STATUS_OPTION_ON_SCENE',
    Complete: 'UPDATE_VISIT_STATUS_OPTION_COMPLETE',
    Committed: 'UPDATE_VISIT_STATUS_OPTION_COMMITTED',
    Archived: 'UPDATE_VISIT_STATUS_OPTION_ARCHIVED'
} as const;
export type UpdateVisitStatusOption = typeof UpdateVisitStatusOption[keyof typeof UpdateVisitStatusOption];


export function UpdateVisitStatusOptionFromJSON(json: any): UpdateVisitStatusOption {
    return UpdateVisitStatusOptionFromJSONTyped(json, false);
}

export function UpdateVisitStatusOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVisitStatusOption {
    return json as UpdateVisitStatusOption;
}

export function UpdateVisitStatusOptionToJSON(value?: UpdateVisitStatusOption | null): any {
    return value as any;
}

