/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MedicalDecisionMaker } from './MedicalDecisionMaker';
import {
    MedicalDecisionMakerFromJSON,
    MedicalDecisionMakerFromJSONTyped,
    MedicalDecisionMakerToJSON,
} from './MedicalDecisionMaker';

/**
 * 
 * @export
 * @interface UpdateMedicalDecisionMakerResponse
 */
export interface UpdateMedicalDecisionMakerResponse {
    /**
     * 
     * @type {MedicalDecisionMaker}
     * @memberof UpdateMedicalDecisionMakerResponse
     */
    medicalDecisionMaker?: MedicalDecisionMaker;
    /**
     * patient_medical_decision_makers is the list of all entities
     * associated with the Patient whose MedicalDecisionMaker was updated.
     * @type {Array<MedicalDecisionMaker>}
     * @memberof UpdateMedicalDecisionMakerResponse
     */
    patientMedicalDecisionMakers?: Array<MedicalDecisionMaker>;
}

/**
 * Check if a given object implements the UpdateMedicalDecisionMakerResponse interface.
 */
export function instanceOfUpdateMedicalDecisionMakerResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateMedicalDecisionMakerResponseFromJSON(json: any): UpdateMedicalDecisionMakerResponse {
    return UpdateMedicalDecisionMakerResponseFromJSONTyped(json, false);
}

export function UpdateMedicalDecisionMakerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMedicalDecisionMakerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medicalDecisionMaker': !exists(json, 'medical_decision_maker') ? undefined : MedicalDecisionMakerFromJSON(json['medical_decision_maker']),
        'patientMedicalDecisionMakers': !exists(json, 'patient_medical_decision_makers') ? undefined : ((json['patient_medical_decision_makers'] as Array<any>).map(MedicalDecisionMakerFromJSON)),
    };
}

export function UpdateMedicalDecisionMakerResponseToJSON(value?: UpdateMedicalDecisionMakerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'medical_decision_maker': MedicalDecisionMakerToJSON(value.medicalDecisionMaker),
        'patient_medical_decision_makers': value.patientMedicalDecisionMakers === undefined ? undefined : ((value.patientMedicalDecisionMakers as Array<any>).map(MedicalDecisionMakerToJSON)),
    };
}

