/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExternalCareProvider } from './ExternalCareProvider';
import {
    ExternalCareProviderFromJSON,
    ExternalCareProviderFromJSONTyped,
    ExternalCareProviderToJSON,
} from './ExternalCareProvider';

/**
 * 
 * @export
 * @interface UpdateExternalCareProviderResponse
 */
export interface UpdateExternalCareProviderResponse {
    /**
     * 
     * @type {ExternalCareProvider}
     * @memberof UpdateExternalCareProviderResponse
     */
    externalCareProvider?: ExternalCareProvider;
    /**
     * patient_external_care_providers is the list of providers associated
     * with patient whose ExternalCareProvider was just updated.
     * @type {Array<ExternalCareProvider>}
     * @memberof UpdateExternalCareProviderResponse
     */
    patientExternalCareProviders?: Array<ExternalCareProvider>;
}

/**
 * Check if a given object implements the UpdateExternalCareProviderResponse interface.
 */
export function instanceOfUpdateExternalCareProviderResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateExternalCareProviderResponseFromJSON(json: any): UpdateExternalCareProviderResponse {
    return UpdateExternalCareProviderResponseFromJSONTyped(json, false);
}

export function UpdateExternalCareProviderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateExternalCareProviderResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalCareProvider': !exists(json, 'external_care_provider') ? undefined : ExternalCareProviderFromJSON(json['external_care_provider']),
        'patientExternalCareProviders': !exists(json, 'patient_external_care_providers') ? undefined : ((json['patient_external_care_providers'] as Array<any>).map(ExternalCareProviderFromJSON)),
    };
}

export function UpdateExternalCareProviderResponseToJSON(value?: UpdateExternalCareProviderResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'external_care_provider': ExternalCareProviderToJSON(value.externalCareProvider),
        'patient_external_care_providers': value.patientExternalCareProviders === undefined ? undefined : ((value.patientExternalCareProviders as Array<any>).map(ExternalCareProviderToJSON)),
    };
}

