/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Episode } from './Episode';
import {
    EpisodeFromJSON,
    EpisodeFromJSONTyped,
    EpisodeToJSON,
} from './Episode';
import type { Patient } from './Patient';
import {
    PatientFromJSON,
    PatientFromJSONTyped,
    PatientToJSON,
} from './Patient';
import type { Visit } from './Visit';
import {
    VisitFromJSON,
    VisitFromJSONTyped,
    VisitToJSON,
} from './Visit';

/**
 * 
 * @export
 * @interface VirtualAPPVisit
 */
export interface VirtualAPPVisit {
    /**
     * 
     * @type {Visit}
     * @memberof VirtualAPPVisit
     */
    visit?: Visit;
    /**
     * 
     * @type {Patient}
     * @memberof VirtualAPPVisit
     */
    patient?: Patient;
    /**
     * 
     * @type {Episode}
     * @memberof VirtualAPPVisit
     */
    episode?: Episode;
}

/**
 * Check if a given object implements the VirtualAPPVisit interface.
 */
export function instanceOfVirtualAPPVisit(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VirtualAPPVisitFromJSON(json: any): VirtualAPPVisit {
    return VirtualAPPVisitFromJSONTyped(json, false);
}

export function VirtualAPPVisitFromJSONTyped(json: any, ignoreDiscriminator: boolean): VirtualAPPVisit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'visit': !exists(json, 'visit') ? undefined : VisitFromJSON(json['visit']),
        'patient': !exists(json, 'patient') ? undefined : PatientFromJSON(json['patient']),
        'episode': !exists(json, 'episode') ? undefined : EpisodeFromJSON(json['episode']),
    };
}

export function VirtualAPPVisitToJSON(value?: VirtualAPPVisit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'visit': VisitToJSON(value.visit),
        'patient': PatientToJSON(value.patient),
        'episode': EpisodeToJSON(value.episode),
    };
}

