/* tslint:disable */
/* eslint-disable */
/**
 * caremanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VisitStatusGroup = {
    Unspecified: 'VISIT_STATUS_GROUP_UNSPECIFIED',
    Active: 'VISIT_STATUS_GROUP_ACTIVE',
    Upcoming: 'VISIT_STATUS_GROUP_UPCOMING',
    Past: 'VISIT_STATUS_GROUP_PAST'
} as const;
export type VisitStatusGroup = typeof VisitStatusGroup[keyof typeof VisitStatusGroup];


export function VisitStatusGroupFromJSON(json: any): VisitStatusGroup {
    return VisitStatusGroupFromJSONTyped(json, false);
}

export function VisitStatusGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisitStatusGroup {
    return json as VisitStatusGroup;
}

export function VisitStatusGroupToJSON(value?: VisitStatusGroup | null): any {
    return value as any;
}

