export enum UserRoles {
  ADMIN = 'admin',
  ADVANCED_CARE = 'advanced-care',
  API = 'api',
  BETA = 'beta',
  CARE_MANAGER = 'caremanager',
  CHANNEL_ADMIN = 'channel-admin',
  CSC = 'csc',
  DEVELOPER = 'developer',
  DH_SERVER = 'dh-server',
  EXPRESS_SUPER_ADMIN = 'express-super-admin',
  INSURANCE_ADMIN = 'insurance-admin',
  INSURANCE_READER = 'insurance-reader',
  LAB_ADMIN = 'lab-admin',
  LEGAL_ADMIN = 'legal-admin',
  MODALITY_ADMIN = 'modality-admin',
  OPTIMIZER = 'optimizer',
  POP_HEALTH_ADMIN = 'pop-health-admin',
  PROTOCOL_AUTHOR = 'protocol-author',
  PROTOCOL_READER = 'protocol-reader',
  PROVIDER = 'provider',
  ROLE_ADMIN = 'role-admin',
  SAFETY_TEAM_ADMIN = 'safety-team-admin',
  SCREENER = 'screener',
  USER = 'user',
  VISIT_SCHEDULER = 'visit-scheduler',
}

export enum MarketRole {
  LeadAPP = 'Lead APP',
  LeadDHMT = 'Lead DHMT',
  MarketManager = 'Market Manager',
  AreaManager = 'Area Manager',
  RDO = 'RDO',
  RMD = 'RMD',
  APP = 'APP',
  DHMT = 'DHMT',
}
