export const REQUEST_PERSONAL_INFO_TEST_IDS = {
  PERSONAL_INFO_HEADER: 'personal-info-header',
  CONTINUE_BUTTON: 'continue-button',
  PERSONAL_INFO_DETAILS_LABEL: 'personal-info-details-label',
  RELATIONSHIP_LABEL: 'relationship-label',
  RELATIONSHIP_DROPDOWN: 'relationship-dropdown',
  RELATIONSHIP_DROPDOWN_OPTION_DEFAULT: 'relationship-dropdown-option-default',
  RELATIONSHIP_DROPDOWN_OPTION_FAMILY_FRIEND:
    'relationship-dropdown-option-family-friend',
  RELATIONSHIP_DROPDOWN_OPTION_CLINICIAN_ORGANIZATION:
    'relationship-dropdown-option-clinician-organization',
  RELATIONSHIP_DROPDOWN_OPTION_OTHER: 'relationship-dropdown-option-other',
  FULL_NAME_LABEL: 'full-name-label',
  FIRST_NAME_FIELD: 'first-name-field',
  FIRST_NAME_INPUT: 'first-name-input',
  LAST_NAME_FIELD: 'last-name-field',
  LAST_NAME_INPUT: 'last-name-input',
  DATE_OF_BIRTH_LABEL: 'date-of-birth-label',
  DATE_OF_BIRTH_FIELD: 'date-of-birth-field',
  DATE_OF_BIRTH_INPUT: 'date-of-birth-input',
  LEGAL_SEX_LABEL: 'legal-sex-label',
  LEGAL_SEX_DROPDOWN: 'legal-sex-dropdown',
  LEGAL_SEX_DROPDOWN_OPTION_DEFAULT: 'legal-sex-dropdown-option-default',
  LEGAL_SEX_DROPDOWN_OPTION_MALE: 'legal-sex-dropdown-option-male',
  LEGAL_SEX_DROPDOWN_OPTION_FEMALE: 'legal-sex-dropdown-option-female',
  LEGAL_SEX_INSURANCE_LABEL: 'legal-sex-insurance-label',
  PHONE_NUMBER_LABEL: 'phone-number-label',
  PHONE_NUMBER_FIELD: 'phone-number-field',
  PHONE_NUMBER_INPUT: 'phone-number-input',
};
