#!/bin/sh

OPTIMIZER_SETTINGS_POLL_INTERVAL="${OPTIMIZER_SETTINGS_POLL_INTERVAL:-0}"
GRPC_SERVER_PER_CALL_TIMEOUT="${GRPC_SERVER_PER_CALL_TIMEOUT:-0}"
DB_POOL_STATS_REPORT_INTERVAL="${DB_POOL_STATS_REPORT_INTERVAL:-0}"
USE_GOOGLE_MAPS_DISTANCES="${USE_GOOGLE_MAPS_DISTANCES:-false}"
GOOGLE_MAPS_CLIENT_TYPE="${GOOGLE_MAPS_CLIENT_TYPE:-distance-matrix-http}"
STATSIG_OPTIMIZER_SETTINGS_REFRESH_INTERVAL="${STATSIG_OPTIMIZER_SETTINGS_REFRESH_INTERVAL:-0}"
GOOGLE_MAPS_MATRIX_REQUESTS_PER_SEC_LIMIT="${GOOGLE_MAPS_MATRIX_REQUESTS_PER_SEC_LIMIT:-0}"
GOOGLE_MAPS_MATRIX_ELEMENTS_PER_SEC_LIMIT="${GOOGLE_MAPS_MATRIX_ELEMENTS_PER_SEC_LIMIT:-0}"
GOOGLE_MAPS_ROUTE_REQUESTS_PER_SEC_LIMIT="${GOOGLE_MAPS_ROUTE_REQUESTS_PER_SEC_LIMIT:-0}"
GRPC_ROUND_ROBIN="${GRPC_ROUND_ROBIN:-false}"
LOCK_DB_POOL_QUERY_TIMEOUT="${LOCK_DB_POOL_QUERY_TIMEOUT:-5m}"

/app \
  "--station-grpc-addr=$STATION_GRPC_ADDR" \
  "--optimizer-settings-poll-interval=$OPTIMIZER_SETTINGS_POLL_INTERVAL" \
  "--optimizer-grpc-addr=$OPTIMIZER_GRPC_ADDR" \
  "--auth0-issuer-url=$AUTH0_ISSUER_URL" \
  "--osrm-addr=$OSRM_ADDR" \
  "--use-google-maps=$USE_GOOGLE_MAPS_DISTANCES" \
  "--google-maps-client-type=$GOOGLE_MAPS_CLIENT_TYPE" \
  "--grpc-server-per-call-timeout=$GRPC_SERVER_PER_CALL_TIMEOUT" \
  "--grpc-server-per-call-timeout-ignore=$GRPC_SERVER_PER_CALL_TIMEOUT_IGNORE"\
  "--db-pool-stats-report-interval=$DB_POOL_STATS_REPORT_INTERVAL" \
  "--lock-db-pool-query-timeout=$LOCK_DB_POOL_QUERY_TIMEOUT" \
  "--statsig-optimizer-settings-refresh-interval=$STATSIG_OPTIMIZER_SETTINGS_REFRESH_INTERVAL" \
  "--google-maps-matrix-reqs-per-sec-limit=$GOOGLE_MAPS_MATRIX_REQUESTS_PER_SEC_LIMIT" \
  "--google-maps-matrix-elements-per-sec-limit=$GOOGLE_MAPS_MATRIX_ELEMENTS_PER_SEC_LIMIT" \
  "--google-maps-route-reqs-per-sec-limit=$GOOGLE_MAPS_ROUTE_REQUESTS_PER_SEC_LIMIT" \
  "--grpc-round-robin=$GRPC_ROUND_ROBIN"
