export const PATIENT_MENU_LIST_ITEM_SECTIONS_IDS = {
  NAME: 'NAME',
  EMAIL: 'EMAIL',
  PHONE_NUMBER: 'PHONE_NUMBER',
  DOB: 'DOB',
  LEGAL_SEX: 'LEGAL_SEX',
  ASSIGNED_SEX_AT_BIRTH: 'ASSIGNED_SEX_AT_BIRTH',
  GENDER_IDENTITY: 'GENDER_IDENTITY',
  BILLING_ADDRESS: 'BILLING_ADDRESS',
};

export const PATIENT_MENU_LIST_ITEM_SECTIONS_LABELS = {
  [PATIENT_MENU_LIST_ITEM_SECTIONS_IDS.NAME]: 'Name',
  [PATIENT_MENU_LIST_ITEM_SECTIONS_IDS.EMAIL]: 'Email',
  [PATIENT_MENU_LIST_ITEM_SECTIONS_IDS.PHONE_NUMBER]: 'Phone Number',
  [PATIENT_MENU_LIST_ITEM_SECTIONS_IDS.DOB]: 'Date of Birth',
  [PATIENT_MENU_LIST_ITEM_SECTIONS_IDS.LEGAL_SEX]: 'Legal Sex',
  [PATIENT_MENU_LIST_ITEM_SECTIONS_IDS.ASSIGNED_SEX_AT_BIRTH]:
    'Assigned Sex at Birth',
  [PATIENT_MENU_LIST_ITEM_SECTIONS_IDS.GENDER_IDENTITY]: 'Gender Identity',
  [PATIENT_MENU_LIST_ITEM_SECTIONS_IDS.BILLING_ADDRESS]: 'Billing Address',
};
