---
app: services
auto_deploy: true
context: *company-data-covered*-release-us-east-1
domain: release.*company-data-covered*.com
repo_name: *company-data-covered*/services
hostnames:
  - logistics-service: logistics-service-${env_id}.${domain}
  - clinicalkpi-service: clinicalkpi-service-${env_id}.${domain}
  - patients-service: patients-service-${env_id}.${domain}
  - caremanager-service: caremanager-service-${env_id}.${domain}
  - modality-service: modality-service-${env_id}.${domain}
  - insurance-service: insurance-service-${env_id}.${domain}
  - audit-service: audit-service-${env_id}.${domain}
  - tytocare-service: tytocare-service-${env_id}.${domain}
  - policy-service: policy-service-${env_id}.${domain}
  - onboarding-api: onboarding-api-${env_id}.${domain}
  - riskstratification-service: riskstratification-service-${env_id}.${domain}
  - athena-service: athena-service-${env_id}.${domain}
  - pophealth-service: pophealth-${env_id}.${domain}
  - insurance-dashboard-web: insurance-dashboard-${env_id}.${domain}
  - clinicalkpi-dashboard-web: clinicalkpi-dashboard-${env_id}.${domain}
  - consumer-web: consumer-web-${env_id}.${domain}
environment_templates:
  - name: ephemeral
  - name: permanent
resources:
  cpu:
    limits: 100m
    requests: 10m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
services:
  - name: services-postgres
    image: postgres:14.4-alpine
    has_repo: false
    ports:
      - type: container_port
        port: '5432'
  - name: services-redis
    image: redis:6-alpine
    has_repo: false
    ports:
      - type: container_port
        port: '6379'
  - name: services-elasticsearch
    image: elasticsearch:7.17.5
    has_repo: false
    ports:
      - type: container_port
        port: '9200'
  - name: logistics-service
    image: *company-data-covered*/services/logistics-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8080 8081
        - BUILD_TARGET=logistics-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8080'
        port: '8080'
      - type: node_port
        target_port: '8081'
        port: '8081'
  - name: logistics-optimizer
    image: *company-data-covered*/services/logistics-optimizer
    build:
      dockerfile: './docker/releasehub-java.Dockerfile'
      args:
        - DOCKER_PORT=8081 8181
        - BUILD_TARGET=logistics-optimizer
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8081'
        port: '8081'
      - type: node_port
        target_port: '8181'
        port: '8181'
  - name: clinicalkpi-service
    image: *company-data-covered*/services/clinicalkpi-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8182 8183
        - BUILD_TARGET=clinicalkpi-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8182'
        port: '8182'
      - type: node_port
        target_port: '8183'
        port: '8183'
  - name: patients-service
    image: *company-data-covered*/services/patients-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8182 8183
        - BUILD_TARGET=patients-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8471'
        port: '8471'
      - type: node_port
        target_port: '8473'
        port: '8473'
  - name: caremanager-service
    image: *company-data-covered*/services/caremanager-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8080 8081
        - BUILD_TARGET=caremanager-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8080'
        port: '8080'
      - type: node_port
        target_port: '8081'
        port: '8081'
  - name: modality-service
    image: *company-data-covered*/services/modality-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8092 8093
        - BUILD_TARGET=modality-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8092'
        port: '8092'
      - type: node_port
        target_port: '8093'
        port: '8093'
  - name: insurance-service
    image: *company-data-covered*/services/insurance-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8096 8097
        - BUILD_TARGET=insurance-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8096'
        port: '8096'
      - type: node_port
        target_port: '8097'
        port: '8097'
  - name: audit-service
    image: *company-data-covered*/services/audit-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8482
        - BUILD_TARGET=audit-service
    has_repo: true
    static: false
    ports:
      - type: container_port
        target_port: '8482'
        port: '8482'
  - name: tytocare-service
    image: *company-data-covered*/services/tytocare-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8090 8091
        - BUILD_TARGET=tytocare-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8090'
        port: '8090'
      - type: node_port
        target_port: '8091'
        port: '8091'
  - name: riskstratification-service
    image: *company-data-covered*/services/riskstratification-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8094 8095
        - BUILD_TARGET=riskstratification-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8094'
        port: '8094'
      - type: node_port
        target_port: '8095'
        port: '8095'
  - name: athena-service
    image: *company-data-covered*/services/athena-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8182 8472
        - BUILD_TARGET=athena-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8182'
        port: '8182'
      - type: node_port
        target_port: '8472'
        port: '8472'
  - name: pophealth-service
    image: *company-data-covered*/services/pophealth-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8080 8081
        - BUILD_TARGET=pophealth-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8080'
        port: '8080'
      - type: node_port
        target_port: '8081'
        port: '8081'
  - name: partner-service
    image: *company-data-covered*/services/partner-service
    command:
      - '/busybox/sh'
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/go.Dockerfile'
      args:
        - DOCKER_PORT=8481 8080
        - BUILD_TARGET=partner-service
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8481'
        port: '8481'
      - type: node_port
        target_port: '8080'
        port: '8080'
  - name: policy-service
    image: *company-data-covered*/services/policy-service
    build:
      dockerfile: './docker/opa.Dockerfile'
      args:
        - BUNDLE=opa/bundle
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8181'
        port: '8181'
  - name: onboarding-api
    image: *company-data-covered*/services/onboarding-api
    command:
      - '/entrypoint.sh'
    build:
      dockerfile: './docker/onboarding-api.Dockerfile'
      args:
        - DOCKER_PORT=8080
        - BUILD_TARGET=onboarding-api
    has_repo: true
    static: false
    ports:
      - type: node_port
        target_port: '8080'
        port: '8080'
  - name: insurance-dashboard-web
    build_package_install_command: npm install
    build_command: nx run insurance-dashboard:build:releasehub
    build_output_directory: dist/ts/apps/insurance-dashboard
    static: true
  - name: clinicalkpi-dashboard-web
    build_package_install_command: npm install
    build_command: nx run clinical-kpi:build:releasehub
    build_output_directory: dist/ts/apps/clinical-kpi
    static: true
  - name: consumer-web
    build_package_install_command: npm install
    build_command: nx run consumer-web:build:releasehub
    build_output_directory: dist/ts/apps/consumer-web
    static: true
  - name: logistics-db-migrations
    image: *company-data-covered*/services/logistics-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=logistics
    has_repo: true
    static: false
  - name: audit-db-migrations
    image: *company-data-covered*/services/audit-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=audit
    has_repo: true
    static: false
  - name: clinicalkpi-db-migrations
    image: *company-data-covered*/services/clinicalkpi-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=clinicalkpi
    has_repo: true
    static: false
  - name: caremanager-db-migrations
    image: *company-data-covered*/services/caremanager-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=caremanager
    has_repo: true
    static: false
  - name: modality-db-migrations
    image: *company-data-covered*/services/modality-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=modality
    has_repo: true
    static: false
  - name: insurance-db-migrations
    image: *company-data-covered*/services/insurance-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=insurance
    has_repo: true
    static: false
  - name: patients-db-migrations
    image: *company-data-covered*/services/patients-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=patients
    has_repo: true
    static: false
  - name: riskstratification-db-migrations
    image: *company-data-covered*/services/riskstratification-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=riskstratification
    has_repo: true
    static: false
  - name: pophealth-db-migrations
    image: *company-data-covered*/services/pophealth-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=pophealth
    has_repo: true
    static: false
  - name: partner-db-migrations
    image: *company-data-covered*/services/partner-db-migrations
    build:
      dockerfile: './docker/releasehub-tooling.Dockerfile'
      args:
        - DATABASE_NAME=partner
    has_repo: true
    static: false
jobs:
  - name: ensure-logistics-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $DATABASE_NAME' WHERE NOT EXISTS (SELECT FROM pg_database
        WHERE datname = '$DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-audit-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $AUDIT_DATABASE_NAME' WHERE NOT EXISTS (SELECT FROM
        pg_database WHERE datname = '$AUDIT_DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-clinicalkpi-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $CLINICALKPI_DATABASE_NAME' WHERE NOT EXISTS (SELECT
        FROM pg_database WHERE datname = '$CLINICALKPI_DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-caremanager-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $CAREMANAGER_DATABASE_NAME' WHERE NOT EXISTS (SELECT
        FROM pg_database WHERE datname = '$CAREMANAGER_DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-modality-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $MODALITY_DATABASE_NAME' WHERE NOT EXISTS (SELECT
        FROM pg_database WHERE datname = '$MODALITY_DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-insurance-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $INSURANCE_DATABASE_NAME' WHERE NOT EXISTS (SELECT
        FROM pg_database WHERE datname = '$INSURANCE_DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-patients-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $PATIENT_DATABASE_NAME' WHERE NOT EXISTS (SELECT
        FROM pg_database WHERE datname = '$PATIENT_DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-riskstratification-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $RISKSTRATIFICATION_DATABASE_NAME' WHERE NOT EXISTS
        (SELECT FROM pg_database WHERE datname = '$RISKSTRATIFICATION_DATABASE_NAME')\gexec"
        | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-pophealth-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $POPHEALTH_DATABASE_NAME' WHERE NOT EXISTS (SELECT
        FROM pg_database WHERE datname = '$POPHEALTH_DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: ensure-partner-db
    command:
      - sh
      - '-c'
      - echo "SELECT 'CREATE DATABASE $PARTNER_DATABASE_NAME' WHERE NOT EXISTS (SELECT
        FROM pg_database WHERE datname = '$PARTNER_DATABASE_NAME')\gexec" | psql $DATABASE_URL
    from_services: services-postgres
  - name: logistics-db-migrations
    from_services: logistics-db-migrations
  - name: audit-db-migrations
    from_services: audit-db-migrations
  - name: clinicalkpi-db-migrations
    from_services: clinicalkpi-db-migrations
  - name: caremanager-db-migrations
    from_services: caremanager-db-migrations
  - name: modality-db-migrations
    from_services: modality-db-migrations
  - name: insurance-db-migrations
    from_services: insurance-db-migrations
  - name: patients-db-migrations
    from_services: patients-db-migrations
  - name: riskstratification-db-migrations
    from_services: riskstratification-db-migrations
  - name: pophealth-db-migrations
    from_services: pophealth-db-migrations
  - name: partner-db-migrations
    from_services: partner-db-migrations
workflows:
  - name: setup
    parallelize:
      - step: databases
        tasks:
          - services.services-postgres
          - services.services-redis
          - services.services-elasticsearch
      - step: ensure-databases
        tasks:
          - jobs.ensure-logistics-db
          - jobs.ensure-audit-db
          - jobs.ensure-clinicalkpi-db
          - jobs.ensure-caremanager-db
          - jobs.ensure-modality-db
          - jobs.ensure-insurance-db
          - jobs.ensure-patients-db
          - jobs.ensure-riskstratification-db
          - jobs.ensure-pophealth-db
          - jobs.ensure-partner-db
      - step: run-migrations
        tasks:
          - jobs.logistics-db-migrations
          - jobs.audit-db-migrations
          - jobs.clinicalkpi-db-migrations
          - jobs.caremanager-db-migrations
          - jobs.modality-db-migrations
          - jobs.insurance-db-migrations
          - jobs.patients-db-migrations
          - jobs.riskstratification-db-migrations
          - jobs.pophealth-db-migrations
          - jobs.partner-db-migrations
      - step: start-frontends
        tasks:
          - services.insurance-dashboard-web
          - services.clinicalkpi-dashboard-web
          - services.consumer-web
        wait_for_finish: false
      - step: start-services
        tasks:
          - services.logistics-optimizer
          - services.audit-service
          - services.policy-service
          - services.logistics-service
          - services.clinicalkpi-service
          - services.athena-service
          - services.patients-service
          - services.caremanager-service
          - services.insurance-service
          - services.riskstratification-service
          - services.onboarding-api
          - services.modality-service
          - services.tytocare-service
          - services.pophealth-service
          - services.partner-service
  - name: teardown
    parallelize:
      - step: remove_environment
        tasks:
          - release.remove_environment
  - name: patch
    parallelize:
      - step: run-migrations
        tasks:
          - jobs.logistics-db-migrations
          - jobs.audit-db-migrations
          - jobs.clinicalkpi-db-migrations
          - jobs.caremanager-db-migrations
          - jobs.modality-db-migrations
          - jobs.insurance-db-migrations
          - jobs.patients-db-migrations
          - jobs.pophealth-db-migrations
          - jobs.partner-db-migrations
      - step: start-frontends
        tasks:
          - services.insurance-dashboard-web
          - services.clinicalkpi-dashboard-web
          - services.consumer-web
        wait_for_finish: false
      - step: start-services
        tasks:
          - services.logistics-optimizer
          - services.audit-service
          - services.policy-service
          - services.logistics-service
          - services.clinicalkpi-service
          - services.athena-service
          - services.patients-service
          - services.caremanager-service
          - services.insurance-service
          - services.riskstratification-service
          - services.onboarding-api
          - services.modality-service
          - services.tytocare-service
          - services.pophealth-service
          - services.partner-service
parallelize_app_imports: true
app_imports:
  - name: station
  - name: turf-or-surf
  - name: logistics
  - name: caravan
  - name: websocket-server
  - name: onboarding-web
