version: '3.8'
services:
  osrm-routed:
    container_name: osrm-routed
    image: ghcr.io/project-osrm/osrm-backend

    ports:
      - '5050:5000'
    environment:
      - OSM_FILE_BASE=${OSM_FILE_BASE}
      - OSRM_ALGO=${OSRM_ALGO}
      - OSRM_MAX_TABLE_SIZE=${OSRM_MAX_TABLE_SIZE}

    command: bash /scripts/osrm-routed-entrypoint.sh

    volumes:
      - type: bind
        source: ../../generated/osrm/processed
        target: /data
        read_only: true
      - type: bind
        source: ./logistics/
        target: /scripts
        read_only: true
