import { Meta } from '@storybook/react';

import {
  AccessTimeIcon,
  AccountCircleIcon,
  AddBoxIcon,
  AddIcon,
  ArrowDropDownIcon,
  ArrowForwardIcon,
  ArrowRightAlt,
  ArrowCircleLeftIcon,
  ArrowCircleRightIcon,
  AssignmentIcon,
  Box,
  BrushIcon,
  CallIcon,
  CameraAltIcon,
  ChatIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronRightIcon,
  CircleIcon,
  ClearIcon,
  CloseIcon,
  CloudDownloadIcon,
  CodeIcon,
  CreditCardIcon,
  DeleteIcon,
  DirectionsCarIcon,
  DraftsIcon,
  ExpandMoreIcon,
  FiberManualRecordIcon,
  FilterListIcon,
  HealthAndSafetyIcon,
  HomeIcon,
  InboxIcon,
  InfoIcon,
  InfoOutlinedIcon,
  InsightsIcon,
  LibraryAddIcon,
  LocalHospitalIcon,
  LockIcon,
  MailIcon,
  MapIcon,
  MapsHomeWorkIcon,
  MenuIcon,
  MoreVertIcon,
  NotesIcon,
  PersonIcon,
  PublishIcon,
  PushPinIcon,
  RefreshIcon,
  RoomIcon,
  SearchIcon,
  ShowChartIcon,
  StarIcon,
  StickyNote2Icon,
  TodayIcon,
  WarningIcon,
  EmojiEventsIcon,
  RemoveCircleOutlinedIcon,
  GroupsIcon,
  QuizIcon,
  KeyboardOptionKeyIcon,
  WarningAmberOutlinedIcon,
  TaskAltIcon,
} from '../../../index';

const icons = [
  AccessTimeIcon,
  AccountCircleIcon,
  AddBoxIcon,
  AddIcon,
  ArrowCircleLeftIcon,
  ArrowCircleRightIcon,
  ArrowDropDownIcon,
  ArrowForwardIcon,
  ArrowRightAlt,
  AssignmentIcon,
  BrushIcon,
  CallIcon,
  CameraAltIcon,
  ChatIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronRightIcon,
  CircleIcon,
  ClearIcon,
  CloseIcon,
  CloudDownloadIcon,
  CodeIcon,
  CreditCardIcon,
  DeleteIcon,
  DirectionsCarIcon,
  DraftsIcon,
  ExpandMoreIcon,
  FiberManualRecordIcon,
  FilterListIcon,
  HealthAndSafetyIcon,
  HomeIcon,
  InboxIcon,
  InfoIcon,
  InfoOutlinedIcon,
  InsightsIcon,
  LibraryAddIcon,
  LocalHospitalIcon,
  LockIcon,
  MailIcon,
  MapIcon,
  MapsHomeWorkIcon,
  MenuIcon,
  MoreVertIcon,
  NotesIcon,
  PersonIcon,
  PublishIcon,
  PushPinIcon,
  RefreshIcon,
  RoomIcon,
  SearchIcon,
  ShowChartIcon,
  StarIcon,
  StickyNote2Icon,
  TodayIcon,
  WarningIcon,
  WarningAmberOutlinedIcon,
  EmojiEventsIcon,
  RemoveCircleOutlinedIcon,
  GroupsIcon,
  QuizIcon,
  KeyboardOptionKeyIcon,
  TaskAltIcon,
];

export const AllIcons = () => (
  <Box display="grid" gridTemplateColumns="repeat(12, 1fr)" gap={2}>
    {icons.map((Icon, index) => (
      <Box key={index} gridColumn="span 1">
        <Icon />
      </Box>
    ))}
  </Box>
);

export default {
  title: 'Icons/All',
} as Meta<typeof AllIcons>;
