name: Build Onboarding API

run-name: ${{ github.head_ref || github.ref_name }} (${{ inputs.ref || github.sha }})

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The sha to build, otherwise builds HEAD of branch
        type: string
        required: false

permissions:
  contents: read
  packages: read

jobs:
  build-onboarding-api-container:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Build and Push Docker Container
        uses: ./.github/actions/build_and_push_docker
        with:
          image_name: onboarding-api
          dockerfile: docker/onboarding-api.Dockerfile
          docker_port: 8080
          docker_registry_url: ${{ secrets.DH_DOCKER_REGISTRY_URL }}
          docker_registry_username: ${{ secrets.DH_DOCKER_REGISTRY_PUSH_USERNAME }}
          docker_registry_password: ${{ secrets.DH_DOCKER_REGISTRY_PASSWORD }}
          extra_build_args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
