name: Build Modality Service

run-name: ${{ github.head_ref || github.ref_name }} (${{ inputs.ref || github.sha }})

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The sha to build, otherwise builds HEAD of branch
        type: string
        required: false
  push:
    branches:
      - trunk

jobs:
  build-modality-service-container:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Build and Push Docker Container
        uses: ./.github/actions/build_and_push_docker
        with:
          image_name: modality-service
          dockerfile: docker/go.Dockerfile
          docker_port: 8092 8093
          docker_registry_url: ${{ secrets.DH_DOCKER_REGISTRY_URL }}
          docker_registry_username: ${{ secrets.DH_DOCKER_REGISTRY_PUSH_USERNAME }}
          docker_registry_password: ${{ secrets.DH_DOCKER_REGISTRY_PASSWORD }}
