name: Test OPA

on:
  workflow_call:
  push:
    paths:
      - opa/bundle/**/*.rego
      - .github/workflows/test_opa.yml
    branches:
      - trunk
  pull_request:
    paths:
      - opa/bundle/**/*.rego
      - .github/workflows/test_opa.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-opa:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2

      - name: Lint OPA
        run: make lint-opa

      - name: Test OPA
        run: make test-opa

      - name: Alert on trunk fail
        uses: archive/github-actions-slack@v2.6.0
        if: failure() && github.ref == 'refs/heads/trunk'
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C04C33SCSKC #alert-trunk-services
          slack-text: |
            :this-is-fine: *Trunk GitHub Action Job Failed*
            *Job*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}>
            *Author*: ${{ github.actor }}
